#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

CODEINSIDER_HOME="$XDG_CONFIG_HOME/Code - Insiders/"

install() {
  case $(_os) in
    # macos)  brew tap d12frosted/emacs-plus
    #         brew install emacs-plus --without-spacemacs-icon
    #         ;;
    # arch)   pacaur --needed --noconfirm --noedit -S make emacs ;;
    debian) curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
            sudo apt-get update
            sudo apt-get install code-insiders ;;
  esac
}

# TODO add versions and OS support
update() {
    code-insiders --list-extensions > $CODEINSIDER_HOME/extensionListInsider 
}

link() {
  mklink codeInsider $CODEINSIDER_HOME/settings.json
  mklink extensionListInsider $CODEINSIDER_HOME/extensionListInsider
}

clean() {
  rm -fv $CODEINSIDER_HOME
  rm -fv $CODEINSIDER_HOME/settings.json
}

init "$@"
