# /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding
#   '<Super>c'
# /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command
#   'org-capture'
# /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name
#   'org-capture'
# [org/gnome/settings-daemon/plugins/media-keys]
# custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
# [org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
# binding='<Super>e'
# command='emacsclient --eval "(emacs-everywhere)"'
# name='Emacs Everywhere'
# [org/gnome/desktop/wm/keybindings]
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-1
#   ['<Control><Super>1']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-10
#   ['<Control><Super>0']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-2
#   ['<Control><Super>2']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-3
#   ['<Control><Super>3']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-4
#   ['<Control><Super>4']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-5
#   ['<Control><Super>5']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-6
#   ['<Control><Super>6']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-7
#   ['<Control><Super>7']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-8
#   ['<Control><Super>8']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-9
#   ['<Control><Super>9']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-1
#   ['<Control><Super>KP_1']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-10
#   ['<Control><Super>KP_0']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-2
#   ['<Control><Super>KP_2']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-3
#   ['<Control><Super>KP_3']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-4
#   ['<Control><Super>KP_4']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-5
#   ['<Control><Super>KP_5']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-6
#   ['<Control><Super>KP_6']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-7
#   ['<Control><Super>KP_7']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-8
#   ['<Control><Super>KP_8']
# /org/gnome/shell/extensions/dash-to-panel/app-ctrl-hotkey-kp-9
#   ['<Control><Super>KP_9']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-1
#   ['<Super>1']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-10
#   ['<Super>0']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-2
#   ['<Super>2']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-3
#   ['<Super>3']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-4
#   ['<Super>4']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-5
#   ['<Super>5']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-6
#   ['<Super>6']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-7
#   ['<Super>7']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-8
#   ['<Super>8']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-9
#   ['<Super>9']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-1
#   ['<Super>KP_1']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-10
#   ['<Super>KP_0']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-2
#   ['<Super>KP_2']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-3
#   ['<Super>KP_3']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-4
#   ['<Super>KP_4']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-5
#   ['<Super>KP_5']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-6
#   ['<Super>KP_6']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-7
#   ['<Super>KP_7']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-8
#   ['<Super>KP_8']
# /org/gnome/shell/extensions/dash-to-panel/app-hotkey-kp-9
#   ['<Super>KP_9']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-1
#   ['<Shift><Super>1']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-10
#   ['<Shift><Super>0']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-2
#   ['<Shift><Super>2']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-3
#   ['<Shift><Super>3']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-4
#   ['<Shift><Super>4']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-5
#   ['<Shift><Super>5']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-6
#   ['<Shift><Super>6']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-7
#   ['<Shift><Super>7']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-8
#   ['<Shift><Super>8']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-9
#   ['<Shift><Super>9']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-1
#   ['<Shift><Super>KP_1']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-10
#   ['<Shift><Super>KP_0']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-2
#   ['<Shift><Super>KP_2']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-3
#   ['<Shift><Super>KP_3']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-4
#   ['<Shift><Super>KP_4']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-5
#   ['<Shift><Super>KP_5']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-6
#   ['<Shift><Super>KP_6']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-7
#   ['<Shift><Super>KP_7']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-8
#   ['<Shift><Super>KP_8']
# /org/gnome/shell/extensions/dash-to-panel/app-shift-hotkey-kp-9
#   ['<Shift><Super>KP_9']
# /org/gnome/shell/extensions/dash-to-panel/hotkey-prefix-text
#   'Super'
#
{
  home-manager.users.emiller = {
    # dconf.settings = {
    #   "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0" = {
    #     binding = "<Super>c";
    #     command = "org-capture";
    #     name = "org-capture";
    #   };
    # };
  };
}
