# modules/desktop/term/ghostty.nix
#
# Ghostty terminal emulator configuration
#
# KEY DESIGN DECISION: behavior.conf is read from the static config file and has
# PATH injection appended via nix. This solves the problem where Ghostty's `command`
# directive runs before shell profile loading, so nix paths aren't in PATH and tmux
# isn't found.
#
# The solution: Use Ghostty's `env=PATH=...` directive to explicitly set PATH with
# all nix-managed directories, using ${config.user.name} for multi-host support.
#
# Static config files (keybindings.conf, macos.conf, ui.conf) remain as symlinked
# files for easy direct editing. behavior.conf is also editable in
# config/ghostty/behavior.conf - nix just appends the PATH injection.
#
# The main config file is generated to allow other modules (like pi) to add
# additional config-file includes via modules.desktop.term.ghostty.extraConfigFiles.
{
  config,
  inputs,
  lib,
  isDarwin,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.desktop.term.ghostty;
  inherit (config.dotfiles) configDir;

  # Build PATH with all nix-managed directories
  # This ensures commands like `tmux` are found when Ghostty runs its `command` directive,
  # even though shell profile loading is skipped (--noprofile --norc flags)
  nixPath = concatStringsSep ":" [
    "${config.user.home}/.nix-profile/bin"
    "/etc/profiles/per-user/${config.user.name}/bin"
    "/run/current-system/sw/bin"
    "/nix/var/nix/profiles/default/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];

  # Generate the main config content with base includes + any extra config files
  baseConfig = builtins.readFile "${configDir}/ghostty/config";
  extraIncludes = concatMapStringsSep "\n" (f: "config-file = ${f}") cfg.extraConfigFiles;
  generatedConfig =
    if cfg.extraConfigFiles == [ ] then
      baseConfig
    else
      baseConfig
      + ''

        # Additional config includes (auto-generated by nix)
        ${extraIncludes}
      '';
in
{
  options.modules.desktop.term.ghostty = {
    enable = mkBoolOpt false;
    extraConfigFiles = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "Additional config files to include in the main ghostty config";
    };
  };

  config = mkIf cfg.enable {
    # On macOS, ghostty is installed via Homebrew cask
    # On Linux, use the Nix package
    user.packages = optionals (!isDarwin) [ inputs.ghostty.packages.x86_64-linux.default ];

    # ghostty terminfo isn't supported over ssh, so revert to a known one
    modules.shell.zsh.rcInit = ''
      [ "$TERM" = ghostty ] && [ -n "$SSH_CONNECTION" ] && export TERM=xterm-256color
    '';

    # Symlink individual ghostty config files (NOT recursive to avoid conflict with behavior.conf)
    # behavior.conf is generated separately with PATH injection appended
    # Main config is generated to allow extra config-file includes from other modules
    home-manager.users.${config.user.name} = {
      home.file = {
        ".config/ghostty/keybindings.conf".source = "${configDir}/ghostty/keybindings.conf";
        ".config/ghostty/macos.conf".source = "${configDir}/ghostty/macos.conf";
        ".config/ghostty/ui.conf".source = "${configDir}/ghostty/ui.conf";
      };

      xdg.configFile."ghostty/config".text = generatedConfig;

      # Generate behavior.conf by reading the static file and appending PATH injection
      # This allows editing config/ghostty/behavior.conf directly while still injecting
      # the nix PATH needed for tmux discovery.
      #
      # Why this is needed: Ghostty's `command` directive runs via /usr/bin/login with
      # --noprofile --norc flags, which skips shell profile loading. Without explicit
      # PATH, nix-managed commands like tmux aren't found.
      xdg.configFile."ghostty/behavior.conf".text =
        builtins.readFile "${configDir}/ghostty/behavior.conf"
        + ''

          # ============================================================================
          # PATH injection for nix-managed packages (auto-generated by nix)
          # Edit modules/desktop/term/ghostty.nix to modify this section
          # ============================================================================
          # Ghostty's command runs before shell profiles load (--noprofile --norc),
          # so we explicitly set PATH to include nix-managed directories.
          # This enables commands like `tmux` to be found.
          env=PATH=${nixPath}
        '';
    };
  };
}
