# Nix-managed automations — edit in dotfiles, deploy with hey nuc
# UI-created automations live in automations.yaml (separate)

# --- Goodnight routine ---
- alias: "Goodnight - everything off"
  id: goodnight_everything_off
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight
      to: "on"
  action:
    - action: media_player.turn_off
      target:
        entity_id: media_player.tv
    - action: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: Night

- alias: "Good Morning - reset night mode"
  id: good_morning_reset
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight
      to: "off"
  action:
    - action: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: Home

# --- Movie mode ---
- alias: "Movie mode on"
  id: movie_mode_on
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: "Movie"
  action:
    - action: media_player.turn_on
      target:
        entity_id: media_player.tv

- alias: "Movie mode off"
  id: movie_mode_off
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      from: "Movie"
  action: []
  # Add light restore here when you have smart lights

# --- Away mode ---
- alias: "Away mode - turn off media"
  id: away_mode_media_off
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: "Away"
  action:
    - action: media_player.turn_off
      target:
        entity_id: media_player.tv

# --- TV idle auto-off (2hr) ---
- alias: "TV auto-off after 2 hours idle"
  id: tv_idle_auto_off
  trigger:
    - platform: state
      entity_id: media_player.tv
      to: "idle"
      for:
        hours: 2
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: "Night"
  action:
    - action: media_player.turn_off
      target:
        entity_id: media_player.tv
