#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh


install() {
  _ensure_repo gauteh/gmailieer $ISYNC_HOME/gmailieer

  case "$OSTYPE" in
    darwin*)
      brew install offlineimap notmuch
      # brew install mu --with-emacs
      ;;
    linux*)
      if [[ -f /etc/arch-release ]]; then
        yay --needed --noconfirm -S offlineimap notmuch
      elif [[ -f /etc/debian-release ]]; then
        sudo apt-get install isync notmuch msmtp
      fi
      ;;
  esac

  mkdir -p $MAILDIR/account.gmail
  mkdir -p $MAILDIR/account.oldGmail
  mkdir -p $MAILDIR/account.work
  mkdir -p $MAILDIR/account.school

  cd $ISYNC_HOME/gmailieer
  python setup.py install
}

#update() {}

link() {
  # mklink config $OFFLINEIMAP_HOME/config
  # mklink postsync.sh $OFFLINEIMAP_HOME/postsync.sh
  # mklink offlineimap.py $OFFLINEIMAP_HOME/offlineimap.py
}

clean() {
  # rm -fv $OFFLINEIMAP_HOME
  # rmdir $OFFLINEIMAP_HOME
}

init "$@"
