#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh


install() {
  case "$OSTYPE" in
    macos) brew install offlineimap notmuch
      ;;
    arch) yay --needed --noconfirm -S offlineimap notmuch
      ;;
    debian) sudo apt-get install isync notmuch msmtp-mta
            # sudo snap install bw
      ;;
  esac

  mkdir -p $MAILDIR/gmail
  mkdir -p $MAILDIR/eman
  mkdir -p $MAILDIR/olypsis
  mkdir -p $MAILDIR/utd
}

#update() {}

link() {
  mklink mbsyncrc ~/.mbsyncrc
  mklink msmtprc ~/.msmtprc
  mklink checkmail.service $XDG_CONFIG_HOME/systemd/user/checkmail.service
  mklink checkmail.timer $XDG_CONFIG_HOME/systemd/user/checkmail.timer
  mklink notmuch-config $HOME/.notmuch-config
}

clean() {
  # rm -fv $OFFLINEIMAP_HOME
  # rmdir $OFFLINEIMAP_HOME
}

init "$@"
