#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  if ! nc -z 8.8.8.8 53 >/dev/null 2>&1; then
    >&2 echo "No internet connection"
    return 1
  elif ! sudo apt-get -y update; then
    >&2 echo "Could not update pacman"
    return 2
  fi

  # Core essentials
  sudo apt-get -y wget git curl tree rsync dnsutils


update() {
  sudo apt-get update
  sudo apt-get -y upgrade
}

# link() {}

# clean() {}

init "$@"
