{
  # Homebrew configuration for mactraitorpro
  # This file contains all brew packages and casks

  taps = [
    # "jimeh/emacs-builds"  # Not needed, using Nix emacs instead
    "rockorager/tap"  # Prise terminal multiplexer
    "seqeralabs/tap"
  ];

  brews = [
    # Development tools
    "autoconf"
    "automake"
    "cmake"
    "gcc"
    "git"
    "git-lfs"
    "gh"
    "go"
    "libtool"
    "llvm"
    "m4"
    "make"
    "node"
    "node@20"
    "nim"
    "python@3.10"
    "python@3.12"
    "python@3.13"
    "r"

    # Python tools
    "pipx"
    "ruff"
    "uv"
    "numpy"
    "openblas"

    # JavaScript/Node tools
    "fnm"
    "pnpm"

    # Shell and terminal tools
    "asciinema"
    "rockorager/tap/prise"  # Modern terminal multiplexer
    "bash"
    "bat"
    "btop"
    "coreutils"
    "difftastic"
    "direnv"
    "eza"
    "fd"
    "fish"
    "fzf"
    "glow"
    "lazygit"
    "neovim"
    "ripgrep"
    "sd"
    "shellcheck"
    "shfmt"
    "tealdeer"
    "terminal-notifier"
    "thefuck"
    # "tmux"  # Using Nix-managed tmux for custom config
    "tree"
    "tree-sitter"
    "wget"
    "zoxide"

    # Task management
    "rlwrap"
    "task"
    "taskopen"
    "tasksh"
    "taskwarrior-tui"
    "timewarrior"
    "vit"

    # Cloud and infrastructure
    "awscli"
    "aws-shell"
    "cf-terraforming"
    "cloudflare-wrangler"
    "flyctl"
    "gitpod"

    # Data tools
    "aria2"
    "duckdb"
    "dvc"
    "graphviz"
    "harlequin"
    "label-studio"
    "pandoc"
    "postgresql@14"
    "sqlite"
    "sqruff"

    # Media tools
    "ffmpeg"
    "ffmpegthumbnailer"
    "imagemagick"
    "media-info"
    "mpv"
    "sox"
    "tesseract"
    "yt-dlp"

    # Networking and communication
    "curl"
    "rsync"
    "rclone"
    "wget"

    # Security
    "gnupg"
    "gpgme"
    "rage"

    # Utilities
    "jq"
    "yq"
    "mas"
    "mise"
    "pngpaste"
    "usage"
    "seqeralabs/tap/wave-cli"
    "wimlib"
    "yabai"
    "z3"

    # Libraries and dependencies
    "abseil"
    "aom"
    "apache-arrow"
    "aribb24"
    "aspell"
    "aws-c-auth"
    "aws-c-cal"
    "aws-c-common"
    "aws-c-compression"
    "aws-c-event-stream"
    "aws-c-http"
    "aws-c-io"
    "aws-c-mqtt"
    "aws-c-s3"
    "aws-c-sdkutils"
    "aws-checksums"
    "aws-crt-cpp"
    "aws-sdk-cpp"
    "brotli"
    "c-ares"
    "ca-certificates"
    "cairo"
    "certifi"
    "cffi"
    "cjson"
    "cryptography"
    "dav1d"
    "espeak-ng"
    "flac"
    "fontconfig"
    "freetype"
    "frei0r"
    "fribidi"
    "gd"
    "gdbm"
    "gdk-pixbuf"
    "gettext"
    "ghostscript"
    "giflib"
    "glib"
    "gmp"
    "gnutls"
    "graphite2"
    "grpc"
    "gts"
    "harfbuzz"
    "highway"
    "icu4c@76"
    "icu4c@77"
    "imath"
    "ios-deploy"
    "isl"
    "jasper"
    "jbig2dec"
    "jpeg-turbo"
    "jpeg-xl"
    "krb5"
    "lame"
    "leptonica"
    "libarchive"
    "libass"
    "libassuan"
    "libavif"
    "libb2"
    "libbluray"
    "libde265"
    "libdeflate"
    "libevent"
    "libgcrypt"
    "libgit2"
    "libgpg-error"
    "libheif"
    "libidn"
    "libidn2"
    "libksba"
    "liblqr"
    "libmediainfo"
    "libmicrohttpd"
    "libmms"
    "libmpc"
    "libnghttp2"
    "libnghttp3"
    "libngtcp2"
    "libogg"
    "libomp"
    "libplacebo"
    "libpng"
    "libpq"
    "libraw"
    "librist"
    "librsvg"
    "libsamplerate"
    "libsndfile"
    "libsodium"
    "libsoxr"
    "libssh"
    "libssh2"
    "libtasn1"
    "libtiff"
    "libunibreak"
    "libunistring"
    "libusb"
    "libuv"
    "libvidstab"
    "libvmaf"
    "libvorbis"
    "libvpx"
    "libvterm"
    "libx11"
    "libxau"
    "libxcb"
    "libxdmcp"
    "libxext"
    "libxrender"
    "libyaml"
    "libzen"
    "libzip"
    "little-cms2"
    "lpeg"
    "luajit"
    "luv"
    "lz4"
    "lzo"
    "mad"
    "mbedtls"
    "molten-vk"
    "mpdecimal"
    "mpfr"
    "mpg123"
    "mujs"
    "ncurses"
    "netpbm"
    "nettle"
    "npth"
    "nspr"
    "nss"
    "oniguruma"
    "opencore-amr"
    "openexr"
    "openjpeg"
    "openssl@3"
    "opus"
    "opusfile"
    "p11-kit"
    "pango"
    "pcaudiolib"
    "pcre2"
    "pinentry"
    "pixman"
    "pkgconf"
    "poppler"
    "popt"
    "portaudio"
    "protobuf"
    "pycparser"
    "pygit2"
    "python-packaging"
    "rav1e"
    "re2"
    "readline"
    "rubberband"
    "sdl2"
    "shaderc"
    "shared-mime-info"
    "simdjson"
    "snappy"
    "speex"
    "srt"
    "svt-av1"
    "swiftformat"
    "swiftlint"
    "tcl-tk@8"
    "theora"
    "thrift"
    "tinymist"
    "typst"
    "uchardet"
    "unbound"
    "unibilium"
    "unixodbc"
    "utf8proc"
    "vapoursynth"
    "vulkan-headers"
    "vulkan-loader"
    "webp"
    "x264"
    "x265"
    "xorgproto"
    "xvid"
    "xxhash"
    "xz"
    "zeromq"
    "zimg"
    "zstd"

    # Additional tools not in original list
    "claude-squad"
    "crush"
    "dataline"
    "eask-cli"
    "harper"
    "html2markdown"
  ];

  casks = [
    # Core productivity
    "1password@beta"
    "1password-cli"
    "raycast"
    "bartender"
    "jordanbaird-ice"

    # Communication
    "slack"
    "discord"
    "legcord"
    "microsoft-teams"
    "microsoft-auto-update"
    "zoom"

    # Development
    "ghostty"
    "visual-studio-code"
    "claude"
    "repo-prompt"
    # "emacs-app-pretest"  # Conflicts with emacs-app, using Nix version instead
    "positron"
    "zed"
    "warp@preview"
    "tuist"

    # Browsers
    "google-chrome"
    "orion"
    "vivaldi"
    "zen"

    # Media
    "spotify"
    "vlc"
    "soundsource"
    "subler"
    "openaudible"

    # Productivity & Notes
    "obsidian"
    "logseq"
    "anytype"
    "capacities"
    "heptabase"
    "sunsama"
    "linear-linear"
    "motion"
    "granola"

    # AI Tools
    "chatgpt"
    "boltai"
    "voicenotes"

    # Window Management
    "aerospace"
    "amethyst"

    # Utilities
    "gitify"
    "syncthing"
    "syncthing-app"
    "calibre"
    "inkscape"
    "mactex"
    "mendeley-reference-manager"
    "neohtop"
    "helpwire-operator"
    "bentobox"
    "flashspace"
    "aqua-voice"

    # Fonts
    "font-jetbrains-mono"
    "font-juliamono"
    "font-ia-writer-duo"
    "font-maple-mono"
  ];

  masApps = {
    "Keynote" = 409183694;
    "Numbers" = 409203825;
    "Xcode" = 497799835;
  };
}