#!/bin/sh

#
# Displays
#

nm-applet &

export MONITOR=$(xrandr -q | grep primary | grep ' connected' | cut -d' ' -f1)
bspc monitor $MONITOR -d {1,2,3,4,5}

#
# Aesthetics
#

bspc config split_ratio 0.50
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# bspc config normal_border_color  "$COLOR_0"
# bspc config active_border_color  "$COLOR_0"
# bspc config focused_border_color "$COLOR_0"

bspc config border_width 1
bspc config window_gap 8
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config -m $MONITOR window_gap 12
bspc config -m $MONITOR bottom_padding 0
bspc config -m $MONITOR top_padding 0
bspc config -m $MONITOR left_padding 0
bspc config -m $MONITOR right_padding 0

# Windows won't steal focus
# bspc config ignore_ewmh_focus true

#
# Rules
#

bspc rule -r '*'

# Floating fixes
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a mpv state=floating center=on
bspc rule -a Vlc state=floating monitor=C center=on
bspc rule -a Pinentry state=floating center=on

# Special apps
bspc rule -a Emacs split_ratio=0.25 border=off state=fullscreen
bspc rule -a Gimp desktop=^6
bspc rule -a obs desktop=^6
bspc rule -a feh state=fullscreen
bspc rule -a Screenkey manage=off
bspc rule -a Chromium monitor=L
bspc rule -a Brave monitor=L
bspc rule -a Firefox monitor=L

bspc rule -a discord desktop=^3
bspc rule -a Spotify desktop=^4
