{
  lib,
  cfg,
  pkgs,
  config,
  ...
}:
with lib;
let
  herdrCfg = cfg.herdr;

  herdrBin = if herdrCfg.package != null then "${herdrCfg.package}/bin/herdr" else "herdr";

  launchPath = concatStringsSep ":" [
    "${config.user.home}/.pi/agent/bin"
    "${config.user.home}/.bun/bin"
    "${config.user.home}/.local/bin"
    "${config.user.home}/.pixi/bin"
    "${config.user.home}/.cargo/bin"
    config.dotfiles.binDir
    "${config.user.home}/.nix-profile/bin"
    "/etc/profiles/per-user/${config.user.name}/bin"
    "/run/current-system/sw/bin"
    "/nix/var/nix/profiles/default/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];
in
mkIf herdrCfg.enable {
  user.packages = optional (herdrCfg.package != null) herdrCfg.package;

  home.configFile =
    optionalAttrs (herdrCfg.configFile != null) {
      "herdr/config.toml".source = herdrCfg.configFile;
    }
    // {
      "tmux/open-herdr.sh" = {
        executable = true;
        text = ''
          #!${pkgs.bash}/bin/bash
          set -euo pipefail

          if [[ -n "''${PATH:-}" ]]; then
            export PATH='${launchPath}':"$PATH"
          else
            export PATH='${launchPath}'
          fi

          # Start from home so herdr doesn't land in '/' when Ghostty launches from Finder.
          cd "$HOME"

          herdr_cmd='${herdrBin}'

          if command -v "$herdr_cmd" >/dev/null 2>&1; then
            if "$herdr_cmd"; then
              exit 0
            fi
          fi

          # Safety fallback: if herdr is unavailable or fails, drop into normal tmux.
          exec tmux new-session -A -s home
        '';
      };

      "tmux/herdr.conf".text = ''
        # Optional herdr integration (generated by nix)
        bind-key ${herdrCfg.key} display-popup -E -w ${toString herdrCfg.popupWidth}% -h ${toString herdrCfg.popupHeight}% "$TMUX_HOME/open-herdr.sh"
      '';
    };

  modules.shell.tmux.rcFiles = mkAfter [ "${config.user.home}/.config/tmux/herdr.conf" ];
}
