{
  lib,
  cfg,
  pkgs,
  config,
  ...
}:
with lib;
let
  jmuxCfg = cfg.jmux;

  jmuxBin =
    if jmuxCfg.package != null then "${jmuxCfg.package}/bin/${jmuxCfg.command}" else jmuxCfg.command;

  launchPath = concatStringsSep ":" [
    "${config.user.home}/.pi/agent/bin"
    "${config.user.home}/.bun/bin"
    "${config.user.home}/.local/bin"
    "${config.user.home}/.pixi/bin"
    "${config.user.home}/.cargo/bin"
    config.dotfiles.binDir
    "${config.user.home}/.nix-profile/bin"
    "/etc/profiles/per-user/${config.user.name}/bin"
    "/run/current-system/sw/bin"
    "/nix/var/nix/profiles/default/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];
in
mkIf jmuxCfg.enable {
  user.packages = optional (jmuxCfg.package != null) jmuxCfg.package;
  environment.shellAliases = optionalAttrs (jmuxCfg.package != null) {
    jmux = jmuxBin;
  };

  home.configFile =
    optionalAttrs (jmuxCfg.configFile != null) {
      "jmux/config.json".source = jmuxCfg.configFile;
    }
    // {
      "tmux/open-jmux.sh" = {
        executable = true;
        text = ''
          #!${pkgs.bash}/bin/bash
          set -euo pipefail

          if [[ -n "''${PATH:-}" ]]; then
            export PATH='${launchPath}':"$PATH"
          else
            export PATH='${launchPath}'
          fi

          # Start from home so jmux doesn't land in '/' when Ghostty launches from Finder.
          cd "$HOME"

          jmux_cmd='${jmuxBin}'

          # jmux reads ~/.config/jmux/config.json automatically when present.
          if command -v "$jmux_cmd" >/dev/null 2>&1; then
            if "$jmux_cmd"; then
              exit 0
            fi
          fi

          # Safety fallback: if jmux is unavailable or fails to start, drop into normal tmux.
          exec tmux new-session -A -s home
        '';
      };

      "tmux/jmux-aliases.zsh".text = ''
        alias jmux='${jmuxBin}'
      '';

      "tmux/jmux.conf".text = ''
        # Optional jmux integration (generated by nix)
        bind-key ${jmuxCfg.key} display-popup -E -w ${toString jmuxCfg.popupWidth}% -h ${toString jmuxCfg.popupHeight}% "$TMUX_HOME/open-jmux.sh"
      '';
    };

  modules.shell.tmux.rcFiles = mkAfter [ "${config.user.home}/.config/tmux/jmux.conf" ];
  modules.shell.zsh.rcFiles = mkAfter (
    optional (jmuxCfg.package != null) "${config.user.home}/.config/tmux/jmux-aliases.zsh"
  );
}
