{
  config,
  pkgs,
  lib,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.shell.tmux;
  inherit (config.dotfiles) configDir;

  opensessionsRuntimeRoot = "${config.user.home}/.local/share/opensessions";
  opensessionsCheckout = "${opensessionsRuntimeRoot}/${pkgs.my.opensessions.version}";
  opensessionsCurrent = "${opensessionsRuntimeRoot}/current";

  opensessionsConfigJson = builtins.toJSON {
    mux = "tmux";
    plugins = [ ];
    inherit (cfg.opensessions) theme;
    sidebarWidth = cfg.opensessions.width;
    inherit (cfg.opensessions) sidebarPosition;
    inherit (cfg.opensessions) showWindowDetails;
  };

  seshConfig =
    let
      ds = cfg.sesh.defaultSession;
      defaultBlock = optionalString (ds.startup_command != null || ds.preview_command != null) (
        concatStringsSep "\n" (
          [ "[default_session]" ]
          ++ optional (ds.startup_command != null) ''startup_command = "${ds.startup_command}"''
          ++ optional (ds.preview_command != null) ''preview_command = "${ds.preview_command}"''
          ++ [ "" ]
        )
      );
      sessionBlock =
        s:
        concatStringsSep "\n" (
          [
            "[[session]]"
            ''name = "${s.name}"''
            ''path = "${s.path}"''
          ]
          ++ optional (s.startup_command != null) ''startup_command = "${s.startup_command}"''
        );
      sessionBlocks = concatMapStringsSep "\n\n" sessionBlock cfg.sesh.sessions;
    in
    "# Generated by nix — do not edit\n${defaultBlock}\n${sessionBlocks}\n";

  tmux-dotbar = pkgs.fetchFromGitHub {
    owner = "vaaleyard";
    repo = "tmux-dotbar";
    rev = "f62692501114582aa5311158271ec39402dfcbcd";
    sha256 = "0y9hjw5rxr3684dcg8s5qc7r70p1ai39bjbadmn7vlnn6680qjzy";
  };

  tmux-dark-notify = pkgs.fetchFromGitHub {
    owner = "erikw";
    repo = "tmux-dark-notify";
    rev = "c3f9a42aab305d95260155e14d34cdfdd212d21e";
    sha256 = "1qcqmq2hp8cb80m91bi2ryfgr8r0wgss3h1a4nlxgkx4w37aw1x3";
  };

  tmux-session-dots = pkgs.fetchFromGitHub {
    owner = "jtmcginty";
    repo = "tmux-session-dots";
    rev = "main";
    sha256 = "0c6yby1ing3sdcgzd5k23dr7hzlam1mcs45l9r9ihy18jx6l04k6";
  };

  tmux-agent-status = pkgs.my."tmux-agent-status";

  tmux = pkgs.writeScriptBin "tmux" ''
    #!${pkgs.stdenv.shell}
    export TMUX_HOME="''${TMUX_HOME:-$HOME/.config/tmux}"
    export DOTFILES="''${DOTFILES:-$HOME/.config/dotfiles}"
    export DOTFILES_BIN="''${DOTFILES_BIN:-$DOTFILES/bin}"
    exec ${pkgs.tmux}/bin/tmux -f "$TMUX_HOME/config" "$@"
  '';
in
{
  options.modules.shell.tmux = import ./options {
    inherit lib configDir;
  };

  config = mkIf cfg.enable (mkMerge [
    {
      modules.shell.tmux.jmux.package = mkDefault pkgs.my.jmux;

      user.packages = [
        tmux
        pkgs.my.tmux-file-picker
        pkgs.my.tmux-smooth-scroll
        pkgs.gum
      ]
      ++ optionals cfg.opensessions.enable [
        pkgs.bun
        pkgs.curl
        pkgs.unstable.fzf
      ];

      fonts.packages = [ pkgs.my.agent-icons ];
      modules.desktop.term.ghostty.configInit = mkIf config.modules.desktop.term.ghostty.enable ''
        font-codepoint-map = U+F5000-U+F5003=Agent Icons
      '';

      modules.theme.onReload.tmux = "${tmux}/bin/tmux source-file $TMUX_HOME/extraInit";

      modules.shell.zsh = {
        rcInit = "_cache tmuxifier init -";
        rcFiles = [ "${configDir}/tmux/aliases.zsh" ];
      };

      # jmux only reads ~/.tmux.conf for user overrides; keep a tiny shim to our XDG config.
      home.file = optionalAttrs cfg.jmux.enable {
        ".tmux.conf".text = ''
          source-file "$HOME/.config/tmux/config"
        '';
      };

      home.configFile =
        (import ./home-files {
          inherit
            lib
            cfg
            pkgs
            configDir
            seshConfig
            opensessionsConfigJson
            tmux-dotbar
            tmux-dark-notify
            tmux-session-dots
            tmux-agent-status
            ;
        })
        // {
          "lazygit/tml.yml".source = "${configDir}/lazygit/tml.yml";
        };

      env = {
        PATH = [ "$TMUXIFIER/bin" ];
        TMUX_HOME = "$XDG_CONFIG_HOME/tmux";
        TMUXIFIER = "$XDG_DATA_HOME/tmuxifier";
        TMUXIFIER_LAYOUT_PATH = "$XDG_DATA_HOME/tmuxifier";
      };
    }

    (import ./_jmux.nix {
      inherit
        lib
        cfg
        pkgs
        config
        ;
    })

    (import ./activations {
      inherit
        lib
        cfg
        pkgs
        config
        opensessionsCheckout
        opensessionsCurrent
        opensessionsRuntimeRoot
        opensessionsConfigJson
        ;
    })
  ]);
}
