{
  config,
  pkgs,
  lib,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.shell.tmux;
  inherit (config.dotfiles) configDir;

  opensessionsSource = "${pkgs.my.opensessions}/share/opensessions";
  opensessionsRuntimeRoot = "${config.user.home}/.local/share/opensessions";
  opensessionsCheckout = "${opensessionsRuntimeRoot}/${pkgs.my.opensessions.version}";
  opensessionsCurrent = "${opensessionsRuntimeRoot}/current";

  opensessionsConfigJson = builtins.toJSON {
    mux = "tmux";
    plugins = [ ];
    inherit (cfg.opensessions) theme;
    sidebarWidth = cfg.opensessions.width;
    inherit (cfg.opensessions) sidebarPosition;
    inherit (cfg.opensessions) showWindowDetails;
  };

  # Generate sesh.toml from Nix options
  seshConfig =
    let
      ds = cfg.sesh.defaultSession;
      defaultBlock = optionalString (ds.startup_command != null || ds.preview_command != null) (
        concatStringsSep "\n" (
          [ "[default_session]" ]
          ++ optional (ds.startup_command != null) ''startup_command = "${ds.startup_command}"''
          ++ optional (ds.preview_command != null) ''preview_command = "${ds.preview_command}"''
          ++ [ "" ]
        )
      );
      sessionBlock =
        s:
        concatStringsSep "\n" (
          [
            "[[session]]"
            ''name = "${s.name}"''
            ''path = "${s.path}"''
          ]
          ++ optional (s.startup_command != null) ''startup_command = "${s.startup_command}"''
        );
      sessionBlocks = concatMapStringsSep "\n\n" sessionBlock cfg.sesh.sessions;
    in
    "# Generated by nix — do not edit\n${defaultBlock}\n${sessionBlocks}\n";

  # Fetch tmux-dotbar - minimal dot-separated status bar theme
  tmux-dotbar = pkgs.fetchFromGitHub {
    owner = "vaaleyard";
    repo = "tmux-dotbar";
    rev = "f62692501114582aa5311158271ec39402dfcbcd";
    sha256 = "0y9hjw5rxr3684dcg8s5qc7r70p1ai39bjbadmn7vlnn6680qjzy";
  };

  # Fetch tmux-dark-notify - auto dark/light mode switching on macOS
  tmux-dark-notify = pkgs.fetchFromGitHub {
    owner = "erikw";
    repo = "tmux-dark-notify";
    rev = "c3f9a42aab305d95260155e14d34cdfdd212d21e";
    sha256 = "1qcqmq2hp8cb80m91bi2ryfgr8r0wgss3h1a4nlxgkx4w37aw1x3";
  };

  # Despite tmux/tmux#142, tmux will support XDG in 3.2. Sadly, only 3.0 is
  # available on nixpkgs, and 3.1b on master (tmux/tmux@15d7e56), so I
  # implement it myself:
  # Export environment variables with fallback defaults for when they aren't
  # set (e.g., ghostty launching with --noprofile --norc). These are needed
  # by the tmux config file itself for sourcing extraInit, swap-pane scripts,
  # and the reload binding.
  tmux = pkgs.writeScriptBin "tmux" ''
    #!${pkgs.stdenv.shell}
    export TMUX_HOME="''${TMUX_HOME:-$HOME/.config/tmux}"
    export DOTFILES="''${DOTFILES:-$HOME/.config/dotfiles}"
    export DOTFILES_BIN="''${DOTFILES_BIN:-$DOTFILES/bin}"
    exec ${pkgs.tmux}/bin/tmux -f "$TMUX_HOME/config" "$@"
  '';
in
{
  options.modules.shell.tmux = with types; {
    enable = mkBoolOpt false;
    rcFiles = mkOpt (listOf (either str path)) [ "${configDir}/tmux/theme.conf" ];

    opensessions = {
      enable = mkBoolOpt false;
      key = mkOpt str "";
      focusKey = mkOpt str "";
      prefixKey = mkOpt str "";
      prefixFocusKey = mkOpt str "";
      prefixToggleKey = mkOpt str "";
      prefixIndexKeys = mkOpt str "";
      width = mkOpt int 26;
      sidebarPosition = mkOpt (enum [
        "left"
        "right"
      ]) "right";
      theme = mkOpt str "catppuccin-mocha";
      showWindowDetails = mkBoolOpt true;
      host = mkOpt str "127.0.0.1";
      port = mkOpt int 7391;
    };

    sesh = {
      sessions = mkOpt (listOf (submodule {
        options = {
          name = mkOption {
            type = str;
            description = "Session display name";
          };
          path = mkOption {
            type = str;
            description = "Working directory (supports ~)";
          };
          startup_command = mkOpt (nullOr str) null;
        };
      })) [ ];
      defaultSession = {
        startup_command = mkOpt (nullOr str) null;
        preview_command = mkOpt (nullOr str) null;
      };
    };
  };

  config = mkIf cfg.enable {
    user.packages = [
      tmux

      pkgs.my.tmux-file-picker
      pkgs.my.tmux-smooth-scroll
      pkgs.gum # Interactive CLI for bd-capture popup
    ]
    ++ optionals cfg.opensessions.enable [
      pkgs.bun # opensessions runtime + dependency bootstrap
      pkgs.curl # opensessions server helper + HTTP control
      pkgs.unstable.fzf # opensessions sessionizer popup
    ];

    # Agent Icons font for PUA codepoints (U+F5000–F5003) rendered by Ghostty
    fonts.packages = [ pkgs.my.agent-icons ];
    modules.desktop.term.ghostty.configInit = mkIf config.modules.desktop.term.ghostty.enable ''
      # Map agent icon PUA codepoints to the Agent Icons font
      font-codepoint-map = U+F5000-U+F5003=Agent Icons
    '';

    modules.theme.onReload.tmux = "${tmux}/bin/tmux source-file $TMUX_HOME/extraInit";

    modules.shell.zsh = {
      rcInit = "_cache tmuxifier init -";
      rcFiles = [ "${configDir}/tmux/aliases.zsh" ];
    };

    home.configFile = {
      "tmux/plugins/tmux-which-key/config.yaml".source = "${configDir}/tmux/which-key.yaml";
      "sesh/sesh.toml" = mkIf (cfg.sesh.sessions != [ ]) {
        text = seshConfig;
      };
      "opensessions/plugins/pi.js" = mkIf cfg.opensessions.enable {
        source = "${configDir}/opensessions/plugins/pi.js";
      };
      "opensessions/plugins/hunk.js" = mkIf cfg.opensessions.enable {
        source = "${configDir}/opensessions/plugins/hunk.js";
      };
      "tmux/open-opensessions-config.sh" = mkIf cfg.opensessions.enable {
        executable = true;
        text = ''
          #!${pkgs.bash}/bin/bash
          set -euo pipefail

          config_dir="''${XDG_CONFIG_HOME:-$HOME/.config}/opensessions"
          config_path="$config_dir/config.json"

          ${pkgs.coreutils}/bin/mkdir -p "$config_dir"

          if [[ ! -f "$config_path" ]]; then
            ${pkgs.coreutils}/bin/printf '%s\n' ${escapeShellArg opensessionsConfigJson} > "$config_path"
          fi

          editor="''${VISUAL:-''${EDITOR:-nvim}}"
          exec "$editor" "$config_path"
        '';
      };
      "tmux" = {
        source = "${configDir}/tmux";
        recursive = true;
      };
      # Nix-generated theme files so dark-notify can re-run dotbar on switch
      "tmux/theme-dark-generated.conf".text = ''
        source '${configDir}/tmux/theme-dark.conf'
        run-shell ${tmux-dotbar}/dotbar.tmux
        run-shell ${pkgs.tmuxPlugins.prefix-highlight}/share/tmux-plugins/prefix-highlight/prefix_highlight.tmux
      '';
      "tmux/theme-light-generated.conf".text = ''
        source '${configDir}/tmux/theme-light.conf'
        run-shell ${tmux-dotbar}/dotbar.tmux
        run-shell ${pkgs.tmuxPlugins.prefix-highlight}/share/tmux-plugins/prefix-highlight/prefix_highlight.tmux
      '';
      "tmux/extraInit".text = ''
        # This file is auto-generated by nixos, don't edit by hand!

        # Load theme config FIRST (sets dotbar color options and pane/border styling)
        # Must happen before dotbar.tmux runs to pick up @tmux-dotbar-* options
        ${concatMapStrings (path: ''
          source '${path}'
        '') cfg.rcFiles}

        # tmux-which-key: discoverable keybinding menu
        set -g @tmux-which-key-xdg-enable 1
        run-shell 'chmod -R u+w "$HOME/.local/share/tmux/plugins/tmux-which-key" 2>/dev/null; true'
        run-shell ${pkgs.tmuxPlugins.tmux-which-key}/share/tmux-plugins/tmux-which-key/plugin.sh.tmux

        # Dotbar theme (must run before prefix-highlight)
        run-shell ${tmux-dotbar}/dotbar.tmux

        # Plugins (prefix-highlight can now replace #{prefix_highlight} placeholder)
        run-shell ${pkgs.tmuxPlugins.copycat}/share/tmux-plugins/copycat/copycat.tmux
        run-shell ${pkgs.tmuxPlugins.prefix-highlight}/share/tmux-plugins/prefix-highlight/prefix_highlight.tmux
        run-shell ${pkgs.tmuxPlugins.yank}/share/tmux-plugins/yank/yank.tmux

        # tmux-dark-notify: auto dark/light mode switching (macOS only)
        # Uses generated theme files that re-run dotbar on switch
        # NOTE: Can't use run-shell for main.tmux — its background daemon causes
        # run-shell to hang waiting for child processes. Start it detached instead.
        set -g @dark-notify-theme-path-light '$HOME/.config/tmux/theme-light-generated.conf'
        set -g @dark-notify-theme-path-dark '$HOME/.config/tmux/theme-dark-generated.conf'
        run-shell -b "${tmux-dark-notify}/main.tmux > /dev/null 2>&1"

        # tmux-smooth-scroll: Rust-based smooth scrolling (replaces azorng/tmux-smooth-scroll)
        # Mouse scroll disabled — causes spurious copy-mode entry in Pi panes
        set -g @smooth-scroll-mouse false
        run-shell '${pkgs.my.tmux-smooth-scroll}/bin/tmux-smooth-scroll init'

        # tmux-smart-name: window naming + AI agent status
        run-shell ${pkgs.my.tmux-smart-name}/share/tmux-smart-name/scripts/smart-name.sh

        ${optionalString cfg.opensessions.enable ''
          # opensessions: tmux sidebar + command table
          set -g @opensessions-key "${cfg.opensessions.key}"
          set -g @opensessions-focus-key "${cfg.opensessions.focusKey}"
          set -g @opensessions-prefix-key "${cfg.opensessions.prefixKey}"
          set -g @opensessions-prefix-focus-key "${cfg.opensessions.prefixFocusKey}"
          set -g @opensessions-prefix-toggle-key "${cfg.opensessions.prefixToggleKey}"
          set -g @opensessions-prefix-index-keys "${cfg.opensessions.prefixIndexKeys}"
          set -g @opensessions-width "${toString cfg.opensessions.width}"
          set-environment -g BUN_PATH "${pkgs.bun}/bin/bun"
          set-environment -g OPENSESSIONS_HOST "${cfg.opensessions.host}"
          set-environment -g OPENSESSIONS_PORT "${toString cfg.opensessions.port}"
          set-environment -g OPENSESSIONS_PATH_PREFIX "${pkgs.curl}/bin:${pkgs.unstable.fzf}/bin:${pkgs.bun}/bin"

          run-shell "sh '$TMUX_HOME/opensessions.sh'"

          # Reclaim prefix keys from opensessions — which-key handles discoverability
          unbind -q s
          unbind -q S
          unbind -q o
        ''}
      '';
    };

    home-manager.users.${config.user.name} =
      { lib, ... }:
      {
        home.activation.opensessions-setup = mkIf cfg.opensessions.enable (
          lib.hm.dag.entryAfter [ "writeBoundary" ] ''
            checkout_root="${opensessionsCheckout}"
            current_link="${opensessionsCurrent}"

            ${pkgs.coreutils}/bin/mkdir -p "${opensessionsRuntimeRoot}" "$checkout_root"
            ${pkgs.rsync}/bin/rsync -a --no-perms --delete --exclude node_modules --exclude .git \
              "${opensessionsSource}/" \
              "$checkout_root/"

            # Source is copied from the read-only Nix store; make runtime checkout writable.
            ${pkgs.coreutils}/bin/chmod -R u+w "$checkout_root"

            if [ ! -d "$checkout_root/node_modules" ]; then
              echo "Bootstrapping opensessions dependencies at $checkout_root..." >&2
              if ! (cd "$checkout_root" && ${pkgs.bun}/bin/bun install --silent --frozen-lockfile); then
                echo "Warning: bun install failed; opensessions may be incomplete." >&2
              fi
            fi

            ${pkgs.coreutils}/bin/rm -rf "$current_link"
            ${pkgs.coreutils}/bin/ln -s "$checkout_root" "$current_link"
          ''
        );

        # Seed writable opensessions config (only if absent) so UI theme toggles
        # and other runtime preferences can still be persisted by opensessions.
        home.activation.opensessions-config = mkIf cfg.opensessions.enable (
          lib.hm.dag.entryAfter [ "opensessions-setup" ] ''
            config_dir="$HOME/.config/opensessions"
            config_path="$config_dir/config.json"

            if [ ! -f "$config_path" ]; then
              ${pkgs.coreutils}/bin/mkdir -p "$config_dir"
              ${pkgs.coreutils}/bin/printf '%s\n' ${escapeShellArg opensessionsConfigJson} > "$config_path"
            fi
          ''
        );
      };

    # tml — tmux dev layout: AI tool + lazygit + shell
    # Shell function in config/tml/aliases.zsh (auto-sourced by zsh module)
    home.configFile."lazygit/tml.yml".source = "${configDir}/lazygit/tml.yml";

    env = {
      PATH = [ "$TMUXIFIER/bin" ];
      TMUX_HOME = "$XDG_CONFIG_HOME/tmux";
      TMUXIFIER = "$XDG_DATA_HOME/tmuxifier";
      TMUXIFIER_LAYOUT_PATH = "$XDG_DATA_HOME/tmuxifier";
    };
  };
}
