{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.shell.herdr;
  tmuxEnabled = config.modules.shell.tmux.enable;

  herdrBin = if cfg.package != null then "${cfg.package}/bin/${cfg.command}" else cfg.command;

  launchPath = concatStringsSep ":" [
    "${config.user.home}/.pi/agent/bin"
    "${config.user.home}/.bun/bin"
    "${config.user.home}/.local/bin"
    "${config.user.home}/.pixi/bin"
    "${config.user.home}/.cargo/bin"
    config.dotfiles.binDir
    "${config.user.home}/.nix-profile/bin"
    "/etc/profiles/per-user/${config.user.name}/bin"
    "/run/current-system/sw/bin"
    "/nix/var/nix/profiles/default/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];

  herdrConfigTemplate =
    if cfg.configFile != null then
      cfg.configFile
    else
      pkgs.writeText "herdr-config.toml" ''
        # Seeded by nix. Herdr keeps this file writable after bootstrap.
        [keys]
        prefix = "${cfg.prefix}"
      '';
in
{
  options.modules.shell.herdr = with types; {
    enable = mkBoolOpt false;
    package = mkOpt (nullOr package) null;
    command = mkOpt str "herdr";
    configFile = mkOpt (nullOr (either str path)) null;
    prefix = mkOpt str "ctrl+c";
    key = mkOpt str "H";
    popupWidth = mkOpt int 90;
    popupHeight = mkOpt int 90;
  };

  config = mkIf cfg.enable {
    modules.shell.herdr.package = mkDefault (pkgs.my.herdr or pkgs.herdr or null);

    user.packages = optional (cfg.package != null) cfg.package;

    home.configFile = {
      "tmux/open-herdr.sh" = {
        executable = true;
        text = ''
          #!${pkgs.bash}/bin/bash
          set -euo pipefail

          if [[ -n "''${PATH:-}" ]]; then
            export PATH='${launchPath}':"$PATH"
          else
            export PATH='${launchPath}'
          fi

          # Start from home so herdr doesn't land in '/' when Ghostty launches from Finder.
          cd "$HOME"

          herdr_cmd='${herdrBin}'

          if command -v "$herdr_cmd" >/dev/null 2>&1; then
            if "$herdr_cmd"; then
              exit 0
            fi
          fi

          # Safety fallback: if herdr is unavailable or fails, prefer tmux when present,
          # otherwise drop into the user's login shell.
          if command -v tmux >/dev/null 2>&1; then
            exec tmux new-session -A -s home
          fi

          exec "''${SHELL:-${pkgs.bashInteractive}/bin/bash}" -l
        '';
      };
    }
    // optionalAttrs tmuxEnabled {
      "tmux/herdr.conf".text = ''
        # Optional herdr integration (generated by nix)
        bind-key ${cfg.key} display-popup -E -w ${toString cfg.popupWidth}% -h ${toString cfg.popupHeight}% "$TMUX_HOME/open-herdr.sh"
      '';
    };

    home-manager.users.${config.user.name} =
      { lib, ... }:
      {
        home.activation.herdr-config-bootstrap = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          herdr_dir="$HOME/.config/herdr"
          target="$herdr_dir/config.toml"
          template="${herdrConfigTemplate}"

          ${pkgs.coreutils}/bin/mkdir -p "$herdr_dir"

          # Herdr updates onboarding/settings in config.toml, so keep a writable local
          # copy and only bootstrap from the nix-managed template when needed.
          # TODO: if herdr grows a way to disable onboarding/settings writes, switch
          # this back to a declarative read-only config file.
          if [ -L "$target" ]; then
            tmp="$(${pkgs.coreutils}/bin/mktemp)"
            ${pkgs.coreutils}/bin/cp -L "$target" "$tmp" 2>/dev/null || ${pkgs.coreutils}/bin/cp "$template" "$tmp"
            ${pkgs.coreutils}/bin/rm -f "$target"
            ${pkgs.coreutils}/bin/mv "$tmp" "$target"
          elif [ ! -e "$target" ]; then
            ${pkgs.coreutils}/bin/cp "$template" "$target"
          fi

          ${pkgs.coreutils}/bin/chmod u+w "$target" 2>/dev/null || true

          # Keep the managed prefix in sync even after the initial bootstrap.
          # Herdr's config stays writable for onboarding/settings, so existing
          # files need an explicit upsert rather than only copying the template.
          ${pkgs.python3}/bin/python3 - "$target" ${escapeShellArg cfg.prefix} <<'PY'
          import pathlib
          import sys

          path = pathlib.Path(sys.argv[1])
          prefix = sys.argv[2]
          lines = path.read_text().splitlines()
          out = []
          in_keys = False
          saw_keys = False
          wrote_prefix = False

          for line in lines:
              stripped = line.strip()
              if stripped.startswith("[") and stripped.endswith("]"):
                  if in_keys and not wrote_prefix:
                      out.append(f'prefix = "{prefix}"')
                      wrote_prefix = True
                  in_keys = stripped == "[keys]"
                  saw_keys = saw_keys or in_keys
                  out.append(line)
                  continue

              if in_keys and stripped.startswith("prefix") and "=" in stripped:
                  if not wrote_prefix:
                      out.append(f'prefix = "{prefix}"')
                      wrote_prefix = True
                  continue

              out.append(line)

          if saw_keys and in_keys and not wrote_prefix:
              out.append(f'prefix = "{prefix}"')
              wrote_prefix = True

          if not saw_keys:
              if out and out[-1].strip():
                  out.append("")
              out.extend(["[keys]", f'prefix = "{prefix}"'])

          path.write_text("\n".join(out) + "\n")
          PY
        '';
      };

    modules.shell.tmux.rcFiles = mkIf tmuxEnabled (mkAfter [
      "${config.user.home}/.config/tmux/herdr.conf"
    ]);
  };
}
