# modules/shell/taskwarrior.nix
# TaskWarrior configuration with TaskChampion sync support
{
  config,
  options,
  lib,
  pkgs,
  isDarwin,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.shell.taskwarrior;
  inherit (config.dotfiles) configDir;
  shortcutScriptsDir = "${configDir}/taskwarrior/shortcut-scripts";
in
{
  options.modules.shell.taskwarrior = {
    enable = mkBoolOpt false;
    syncUrl = mkOption {
      type = types.str;
      default = "http://nuc.cinnamon-rooster.ts.net:8080";
      description = "TaskChampion sync server URL";
      example = "http://192.168.1.222:8080";
    };
    defaultContext = mkOption {
      type = types.str;
      default = "home";
      description = "Default taskwarrior context for this host";
      example = "work";
    };
    shortcuts.enable = mkBoolOpt true;
    timewarriorHook.enable = mkBoolOpt true;
  };

  config = mkIf cfg.enable {
    modules.shell.zsh.rcFiles = [ "${configDir}/taskwarrior/aliases.zsh" ];
    # Generate sync.rc with agenix secret path interpolated
    # The agenix secret is configured in modules/agenix.nix
    home-manager.users.${config.user.name} = { config, lib, ... }: {
      xdg.configFile."task/sync.rc".text = ''
        # TaskChampion Sync Configuration
        # Generated by modules/shell/taskwarrior.nix
        #
        # Credentials are decrypted by agenix at login time.
        # See: hosts/shared/secrets/taskchampion-sync.age
        # 1Password backup: "TaskChampion Sync Server" in Private vault

        # Include decrypted credentials (client_id + encryption_secret)
        include ${config.age.secrets.taskchampion-sync.path}

        # Server URL (host-specific)
        sync.server.url=${cfg.syncUrl}
      '';

      # Create writable ~/.taskrc wrapper that includes repo config
      # This allows `task context` to write to ~/.taskrc without polluting the repo
      # Context filters are defined here (not in taskrc) because taskwarrior's config
      # file parser strips parentheses - setting via CLI preserves them correctly
      home.activation.taskwarriorConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        taskrc="$HOME/.taskrc"
        # Remove symlink if it exists (migration from old setup)
        if [ -L "$taskrc" ]; then
          rm -f "$taskrc"
        fi
        # Create wrapper taskrc if it doesn't exist
        if [ ! -f "$taskrc" ]; then
          cat > "$taskrc" << EOF
        # Taskwarrior wrapper config - created by modules/shell/taskwarrior.nix
        # This file can be modified by \`task context\` and other runtime commands
        # Main configuration is included from the dotfiles repo
        include ${configDir}/taskwarrior/taskrc
        context=${cfg.defaultContext}
        EOF
        else
          # Update include path to current nix store on each rebuild
          ${pkgs.gnused}/bin/sed -i "s|^include /nix/store/.*/config/taskwarrior/taskrc|include ${configDir}/taskwarrior/taskrc|" "$taskrc"
        fi

        # Set context filters via CLI to preserve parentheses
        # (taskrc file parsing strips parens, but CLI config preserves them)
        ${pkgs.taskwarrior3}/bin/task config context.work.read '( area:seqera or area:nfcore ) and ( githubtype:pull_request or githubtype.none: or +jira_active ) and -jira_cleanup' 2>/dev/null || true
        ${pkgs.taskwarrior3}/bin/task config context.work.write 'area:seqera' 2>/dev/null || true
        ${pkgs.taskwarrior3}/bin/task config context.home.read '( area:personal or area:family or area:phd ) and githubtype.none:' 2>/dev/null || true
        ${pkgs.taskwarrior3}/bin/task config context.home.write 'area:personal' 2>/dev/null || true
      '';

      # Taskwarrior-TUI shortcut scripts
      # Keybindings: 1=try, o=taskopen, b=beads, S=schedule-today
      # Timewarrior integration uses the on-modify.timewarrior hook (triggered by 's' key)
      xdg.configFile."taskwarrior-tui/shortcut-scripts/taskopen.sh" = mkIf cfg.shortcuts.enable {
        source = "${shortcutScriptsDir}/taskopen.sh";
        executable = true;
      };
      xdg.configFile."taskwarrior-tui/shortcut-scripts/try-workspace.sh" = mkIf cfg.shortcuts.enable {
        source = "${shortcutScriptsDir}/try-workspace.sh";
        executable = true;
      };
      xdg.configFile."taskwarrior-tui/shortcut-scripts/beads-send.sh" = mkIf cfg.shortcuts.enable {
        source = "${shortcutScriptsDir}/beads-send.sh";
        executable = true;
      };
      xdg.configFile."taskwarrior-tui/shortcut-scripts/schedule-today.sh" = mkIf cfg.shortcuts.enable {
        source = "${shortcutScriptsDir}/schedule-today.sh";
        executable = true;
      };

      # Timewarrior integration hooks
      # on-modify.timewarrior: starts/stops time tracking when task start/stop is used
      # on-modify-timewarrior-duration: updates totalactivetime UDA when task is stopped (Bun/TypeScript)
      home.file.".local/share/task/hooks/on-modify.timewarrior" = mkIf cfg.timewarriorHook.enable {
        source = "${pkgs.timewarrior}/share/doc/timew/ext/on-modify.timewarrior";
        executable = true;
      };
      home.file.".local/share/task/hooks/on-modify-timewarrior-duration" = mkIf cfg.timewarriorHook.enable {
        source = "${configDir}/taskwarrior/hooks/on-modify-timewarrior-duration";
        executable = true;
      };
    };
  };
}
