# modules/shell/taskwarrior.nix
# TaskWarrior configuration with TaskChampion sync support
{
  config,
  options,
  lib,
  pkgs,
  isDarwin,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.shell.taskwarrior;
in
{
  options.modules.shell.taskwarrior = {
    enable = mkBoolOpt false;
    syncUrl = mkOption {
      type = types.str;
      default = "http://nuc.cinnamon-rooster.ts.net:8080";
      description = "TaskChampion sync server URL";
      example = "http://192.168.1.222:8080";
    };
  };

  config = mkIf cfg.enable {
    # Generate sync.rc with agenix secret path interpolated
    # The agenix secret is configured in modules/agenix.nix
    home-manager.users.${config.user.name} = { config, ... }: {
      xdg.configFile."task/sync.rc".text = ''
        # TaskChampion Sync Configuration
        # Generated by modules/shell/taskwarrior.nix
        #
        # Credentials are decrypted by agenix at login time.
        # See: hosts/shared/secrets/taskchampion-sync.age
        # 1Password backup: "TaskChampion Sync Server" in Private vault

        # Include decrypted credentials (client_id + encryption_secret)
        include ${config.age.secrets.taskchampion-sync.path}

        # Server URL (host-specific)
        sync.server.url=${cfg.syncUrl}
      '';
    };
  };
}
