# modules/shell/taskwarrior.nix
# TaskWarrior configuration with TaskChampion sync support
{
  config,
  options,
  lib,
  pkgs,
  isDarwin,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.shell.taskwarrior;
  shortcutScriptsDir = "${configDir}/taskwarrior/shortcut-scripts";
in
{
  options.modules.shell.taskwarrior = {
    enable = mkBoolOpt false;
    syncUrl = mkOption {
      type = types.str;
      default = "http://nuc.cinnamon-rooster.ts.net:8080";
      description = "TaskChampion sync server URL";
      example = "http://192.168.1.222:8080";
    };
    defaultContext = mkOption {
      type = types.str;
      default = "home";
      description = "Default taskwarrior context for this host";
      example = "work";
    };
    shortcuts.enable = mkBoolOpt true;
    timewarriorHook.enable = mkBoolOpt true;
  };

  config = mkIf cfg.enable {
    modules.shell.zsh.rcFiles = [ "${configDir}/taskwarrior/aliases.zsh" ];
    # Generate sync.rc with agenix secret path interpolated
    # The agenix secret is configured in modules/agenix.nix
    home-manager.users.${config.user.name} = { config, ... }: {
      xdg.configFile."task/sync.rc".text = ''
        # TaskChampion Sync Configuration
        # Generated by modules/shell/taskwarrior.nix
        #
        # Credentials are decrypted by agenix at login time.
        # See: hosts/shared/secrets/taskchampion-sync.age
        # 1Password backup: "TaskChampion Sync Server" in Private vault

        # Include decrypted credentials (client_id + encryption_secret)
        include ${config.age.secrets.taskchampion-sync.path}

        # Server URL (host-specific)
        sync.server.url=${cfg.syncUrl}
      '';

      xdg.configFile."task/taskrc".source = "${configDir}/taskwarrior/taskrc";

      xdg.configFile."task/context.rc".text = ''
        # Host-specific context
        # Generated by modules/shell/taskwarrior.nix
        # context=${cfg.defaultContext}
      '';

      # Taskwarrior-TUI shortcut scripts
      # Keybindings: 1=try, o=taskopen, b=beads
      # Timewarrior integration uses the on-modify.timewarrior hook (triggered by 's' key)
      xdg.configFile."taskwarrior-tui/shortcut-scripts/taskopen.sh" = mkIf cfg.shortcuts.enable {
        source = "${shortcutScriptsDir}/taskopen.sh";
        executable = true;
      };
      xdg.configFile."taskwarrior-tui/shortcut-scripts/try-workspace.sh" = mkIf cfg.shortcuts.enable {
        source = "${shortcutScriptsDir}/try-workspace.sh";
        executable = true;
      };
      xdg.configFile."taskwarrior-tui/shortcut-scripts/beads-send.sh" = mkIf cfg.shortcuts.enable {
        source = "${shortcutScriptsDir}/beads-send.sh";
        executable = true;
      };

      # Timewarrior integration hook
      # Automatically starts/stops time tracking when task start/stop is used
      home.file.".local/share/task/hooks/on-modify.timewarrior" = mkIf cfg.timewarriorHook.enable {
        source = "${pkgs.timewarrior}/share/doc/timew/ext/on-modify.timewarrior";
        executable = true;
      };
    };
  };
}
