# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5407-9657";
      fsType = "vfat";
    };

  fileSystems."/data/media/movies" =
    { device = "bigdata/media/movies";
      fsType = "zfs";
    };

  fileSystems."/data/media/music" =
    { device = "bigdata/media/music";
      fsType = "zfs";
    };

  fileSystems."/data/media/shows" =
    { device = "bigdata/media/shows";
      fsType = "zfs";
    };

  fileSystems."/data/media/torrents" =
    { device = "bigdata/media/torrents";
      fsType = "zfs";
    };

  fileSystems."/data/mail" =
    { device = "bigdata/mail";
      fsType = "zfs";
    };

  fileSystems."/data/genomics" =
    { device = "bigdata/genomics";
      fsType = "zfs";
    };

  fileSystems."/data/media/books" =
    { device = "bigdata/media/books";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
}
