# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  ## CPU
  nix.maxJobs = lib.mkDefault 16;
  powerManagement.cpuFreqGovernor = "performance";

  ## Ergodox
  my.packages = [ pkgs.teensy-loader-cli ];
  my.alias.teensyload = "sudo teensy-loader-cli -w -v --mcu=atmega32u4";

  ## GPU
  services.xserver.videoDrivers = [ "nvidiaBeta" ];
  hardware.opengl.enable = true;
  # Respect XDG conventions, damn it!
  environment.systemPackages = with pkgs;
    [
      (writeScriptBin "nvidia-settings" ''
        #!${stdenv.shell}
        exec ${config.boot.kernelPackages.nvidia_x11}/bin/nvidia-settings --config="$XDG_CONFIG_HOME/nvidia/settings"
      '')
    ];

  ## Harddrives
  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/home";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5407-9657";
    fsType = "vfat";
  };

  fileSystems."/data/media/movies" = {
    device = "bigdata/media/movies";
    fsType = "zfs";
  };

  fileSystems."/data/media/music" = {
    device = "bigdata/media/music";
    fsType = "zfs";
  };

  fileSystems."/data/media/shows" = {
    device = "bigdata/media/shows";
    fsType = "zfs";
  };

  fileSystems."/data/media/torrents" = {
    device = "bigdata/media/torrents";
    fsType = "zfs";
  };

  fileSystems."/data/mail" = {
    device = "bigdata/mail";
    fsType = "zfs";
  };

  fileSystems."/data/genomics" = {
    device = "bigdata/genomics";
    fsType = "zfs";
  };

  fileSystems."/data/media/books" = {
    device = "bigdata/media/books";
    fsType = "zfs";
  };

  swapDevices = [ ];
}
