# Fix tools for automatic code formatting
# Run with: jj fix
# Run on specific revisions: jj fix -r 'main..@'

[fix.tools.ruff]
command = ["ruff", "format", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]

[fix.tools.ruff-check]
command = ["ruff", "check", "--fix", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]

[fix.tools.snakefmt]
command = ["snakefmt", "-"]
patterns = ["glob:'**/Snakefile'", "glob:'**/*.smk'"]

[fix.tools.nextflow-lint]
command = ["nextflow", "lint", "-"]
patterns = ["glob:'**/*.nf'", "glob:'**/nextflow.config'"]

[fix.tools.prettier]
command = ["prettier", "--stdin-filepath=$path"]
patterns = [
    "glob:'**/*.md'",
    "glob:'**/*.json'",
    "glob:'**/*.yaml'",
    "glob:'**/*.yml'",
    "glob:'**/*.css'",
    "glob:'**/*.html'",
]

[fix.tools.biome]
command = ["biome", "format", "--stdin-file-path=$path"]
patterns = [
    "glob:'**/*.js'",
    "glob:'**/*.jsx'",
    "glob:'**/*.ts'",
    "glob:'**/*.tsx'",
]

[fix.tools.intellij-format]
# IntelliJ IDEA command-line formatter for Groovy
# Adjust path to your IDE installation (idea, webstorm, etc.)
# Note: This requires the file to be written to disk, not stdin
command = ["idea", "format", "$path"]
patterns = ["glob:'**/*.groovy'", "glob:'**/*.gradle'"]

[fix.tools.rustfmt]
command = ["rustfmt", "--edition=2021"]
patterns = ["glob:'**/*.rs'"]

[fix.tools.gofmt]
command = ["gofmt"]
patterns = ["glob:'**/*.go'"]
