#undef DEBOUNCE
#define DEBOUNCE 40

#undef TAPPING_TERM
#define TAPPING_TERM 140

#define USB_SUSPEND_WAKEUP_DELAY 0
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "wagdn/qmvNyL"
#define LAYER_STATE_8BIT

