#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
    macos)  brew tap d12frosted/emacs-plus
            brew install emacs-plus --without-spacemacs-icon
            ;;
    arch)   yay --needed --noconfirm -S make emacs ;;
    debian) sudo add-apt-repository ppa:kelleyk/emacs
            sudo apt-get update
            sudo apt-get install emacs26 ;;
  esac

  _ensure_repo emiller88/doom-emacs-private ~/.config/doom
  _ensure_repo emiller88/doom-emacs ~/.emacs.d && \
    cd ~/.emacs.d \
    && YES=1 make install
}

update() {
  cd ~/.emacs.d && YES=1 make update
}

# link() { }

# clean() { }

init "$@"
