#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)  brew tap d12frosted/emacs-plus
            brew install emacs-plus --without-spacemacs-icon
            ;;
    arch)   pacaur --needed --noconfirm --noedit -S make emacs ;;
    debian) sudo apt-get install -y make emacs ;;
  esac

  _ensure_repo emiller88/doom-emacs-private ~/.config/doom
  _ensure_repo emiller88/doom-emacs ~/.emacs.d && \
    cd ~/.emacs.d \
    && YES=1 make install
}

update() {
  cd ~/.emacs.d && YES=1 make update
  cd ~/.emacs.d/cask && git pull
}

# link() { }

# clean() { }

init "$@"
