#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  if ! nc -z 8.8.8.8 53 >/dev/null 2>&1; then
    >&2 echo "No internet connection"
    return 1
  elif ! sudo apt-get update && apt-get upgrade -y; then
    >&2 echo "Could not update apt-get"
    return 2
  fi

  sudo apt-get install -y silversearcher-ag pass borgbackup 
  termite-install.sh

  # install crontab
  # crontab ./crontab
}
# update() {}

link() {
  mklink xprofile ~/.xprofile
  mklink config/* $XDG_CONFIG_HOME/
  mklink fonts/* $XDG_DATA_HOME/fonts/
}

clean() {
  rm -fv $XDG_DATA_HOME/fonts/*(@N)
  sudo rm -fv /etc/pacman.d/hooks/*(@N)
}

init "$@"
