# callstack-diff (csd) — render and diff static call-stack trees for JS/TS.
#
# Local Bun/TypeScript tool. Dependencies (including the native oxc-parser
# bindings) are pinned in ./bun.nix, generated by bun2nix; regenerate with:
#   nix run github:nix-community/bun2nix -- -l ./bun.lock -o ./bun.nix
{
  lib,
  stdenv,
  makeWrapper,
  bun,
  inputs,
}:

let
  bun2nix = inputs.bun2nix.packages.${stdenv.hostPlatform.system}.default;

  # Ship only the sources Bun needs at runtime; the bun2nix hook provides
  # node_modules, so exclude any dev-installed copy and build detritus.
  src = lib.cleanSourceWith {
    src = ./.;
    filter =
      path: _type:
      let
        base = baseNameOf path;
      in
      base != "node_modules" && base != "result" && !lib.hasSuffix ".log" base;
  };
in
stdenv.mkDerivation {
  pname = "callstack-diff";
  version = "0.1.0";

  inherit src;

  nativeBuildInputs = [
    bun2nix.hook
    makeWrapper
  ];

  bunDeps = bun2nix.fetchBunDeps {
    bunNix = ./bun.nix;
  };

  # Runs TypeScript sources directly on Bun; no bundle step.
  dontBuild = true;

  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    HOME=$TMPDIR $out/bin/csd --help >/dev/null
    runHook postInstallCheck
  '';

  installPhase = ''
    runHook preInstall

    appDir=$out/lib/callstack-diff
    mkdir -p "$appDir" "$out/bin"

    cp -R src package.json bun.lock "$appDir"/
    cp -R node_modules "$appDir/node_modules"

    makeWrapper ${bun}/bin/bun $out/bin/csd \
      --add-flags run \
      --add-flags "$appDir/src/cli.ts"

    runHook postInstall
  '';

  meta = {
    description = "Render and diff static call-stack trees for JS/TS, powered by Oxc";
    longDescription = ''
      csd parses JS/TS with the Oxc parser, builds a static call-stack tree
      from an entry function (grouping if/else/switch into branch nodes), and
      can diff that tree between two git revisions to surface how a change
      reshaped the call graph.
    '';
    homepage = "https://github.com/edmundmiller/dotfiles";
    license = lib.licenses.mit;
    mainProgram = "csd";
    platforms = lib.platforms.unix;
  };
}
