# Generated by Powerlevel10k configuration wizard on 2025-08-12 at 19:45 CDT.
# Based on romkatv/powerlevel10k/config/p10k-pure.zsh, checksum 7533.
# Wizard options: nerdfont-v3 + powerline, small icons, pure, snazzy, rprompt, 12h time,
# 1 line, sparse, transient_prompt, instant_prompt=verbose.
# Type `p10k configure` to generate another config.
#
# Config file for Powerlevel10k with the style of Pure (https://github.com/sindresorhus/pure).
#
# Differences from Pure:
#
#   - Git:
#     - `@c4d3ec2c` instead of something like `v1.4.0~11` when in detached HEAD state.
#     - No automatic `git fetch` (the same as in Pure with `PURE_GIT_PULL=0`).
#
# Apart from the differences listed above, the replication of Pure prompt is exact. This includes
# even the questionable parts. For example, just like in Pure, there is no indication of Git status
# being stale; prompt symbol is the same in command, visual and overwrite vi modes; when prompt
# doesn't fit on one line, it wraps around with no attempt to shorten it.
#
# If you like the general style of Pure but not particularly attached to all its quirks, type
# `p10k configure` and pick "Lean" style. This will give you slick minimalist prompt while taking
# advantage of Powerlevel10k features that aren't present in Pure.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Prompt colors.
  local grey='242'
  local red='#FF5C57'
  local yellow='#F3F99D'
  local blue='#57C7FF'
  local magenta='#FF6AC1'
  local cyan='#9AEDFE'
  local white='#F1F1F0'

  # Left prompt segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # context                 # user@host
    dir                       # current directory
    vcs                       # git status (disabled in jj repos via my_git_formatter)
    jj                        # jj status (André Arko's async implementation)
    nix_shell                 # nix development environment
    virtualenv                # python virtual environment
    node_version              # node.js version for projects
    package                   # package.json version
    terraform                 # terraform workspace
    aws                       # aws profile
    docker_machine            # docker context
    status                    # exit code (only on error)
    prompt_char               # prompt symbol
  )

  # Right prompt segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    taskwarrior               # taskwarrior pending/overdue count
    command_execution_time    # previous command duration
    python_version            # python version
    background_jobs           # running background jobs
    context                   # user@host
    time                      # current time
  )

  # Basic style options that define the overall prompt look.
  typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent background
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # no surrounding whitespace
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # separate segments with a space
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # no end-of-line symbol
  # Enable minimal visual identifiers for better context
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'

  # Add an empty line before each prompt except the first. This doesn't emulate the bug
  # in Pure that makes prompt drift down whenever you use the Alt-C binding from fzf or similar.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Magenta prompt symbol if the last command succeeded.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=$magenta
  # Red prompt symbol if the last command failed.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=$red
  # Default prompt symbol.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  # Prompt symbol in command vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  # Prompt symbol in visual vi mode is the same as in command mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='❮'
  # Prompt symbol in overwrite vi mode is the same as in command mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false

  # ==[ DEVELOPER ENHANCEMENTS ]==
  
  # Transient prompt - makes previous prompts minimal (super clean!)
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  
  # Nix Shell - show when in nix development environment
  typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_NIX_SHELL_CONTENT_EXPANSION='${P9K_NIX_SHELL_NAME}'
  
  # Python Virtual Environment - enhanced styling
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
  
  # Python Version - show python version for projects
  typeset -g POWERLEVEL9K_PYTHON_VERSION_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_PYTHON_VERSION_PROJECT_ONLY=true
  
  # Node Version - show for Node.js projects only
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
  
  # Package Version - show package.json version
  typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=$magenta
  
  # Status - only show exit code on error
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$red
  
  # Background Jobs - show running jobs
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$yellow
  
  # Enhanced Git - more detailed git information
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='✚'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='●'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_ICON='✖'
  typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_ICON='⬆'
  typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_ICON='⬇'
  
  # Command Execution Time - enhanced formatting
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$yellow
  
  # Directory - show more context for development
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3
  
  # AWS - show current AWS profile
  typeset -g POWERLEVEL9K_AWS_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_AWS_CONTENT_EXPANSION='${P9K_AWS_PROFILE//\%/%%}'
  
  # Terraform - show terraform workspace
  typeset -g POWERLEVEL9K_TERRAFORM_FOREGROUND=$magenta
  typeset -g POWERLEVEL9K_TERRAFORM_CONTENT_EXPANSION='${P9K_TERRAFORM_WORKSPACE//\%/%%}'
  
  # Docker Machine - show docker context
  typeset -g POWERLEVEL9K_DOCKER_MACHINE_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_DOCKER_MACHINE_CONTENT_EXPANSION='${P9K_DOCKER_MACHINE_NAME//\%/%%}'
  
  # Custom segment icons for better visual context
  typeset -g POWERLEVEL9K_AWS_VISUAL_IDENTIFIER_EXPANSION='☁️'
  typeset -g POWERLEVEL9K_TERRAFORM_VISUAL_IDENTIFIER_EXPANSION='🏗️'
  typeset -g POWERLEVEL9K_DOCKER_MACHINE_VISUAL_IDENTIFIER_EXPANSION='🐳'
  typeset -g POWERLEVEL9K_NIX_SHELL_VISUAL_IDENTIFIER_EXPANSION='❄️'
  typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='🐍'
  typeset -g POWERLEVEL9K_NODE_VERSION_VISUAL_IDENTIFIER_EXPANSION='⬢'
  typeset -g POWERLEVEL9K_PYTHON_VERSION_VISUAL_IDENTIFIER_EXPANSION='🐍'
  typeset -g POWERLEVEL9K_PACKAGE_VISUAL_IDENTIFIER_EXPANSION='📦'
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='⚙️'

  # ==[ TASKWARRIOR SEGMENT ]==
  # Show pending task count with overdue indicator
  typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_TASKWARRIOR_VISUAL_IDENTIFIER_EXPANSION='󰱒'
  # Format: "!3/28" if overdue tasks exist, otherwise just "28"
  typeset -g POWERLEVEL9K_TASKWARRIOR_CONTENT_EXPANSION='${P9K_TASKWARRIOR_OVERDUE_COUNT:+"!$P9K_TASKWARRIOR_OVERDUE_COUNT/"}$P9K_TASKWARRIOR_PENDING_COUNT'

  # Don't show Python version in virtualenv (we have separate python_version segment)
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false

  # Blue current directory.
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$blue

  # Context format when root: user@host. The first part white, the rest grey.
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE="%F{$white}%n%f%F{$grey}@%m%f"
  # Context format when not root: user@host. The whole thing grey.
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%F{$grey}%n@%m%f"
  # Don't show context unless root or in SSH.
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_CONTENT_EXPANSION=

  # Show previous command duration only if it's >= 5s.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
  # Don't show fractional seconds. Thus, 7s rather than 7.3s.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  # Duration format: 1d 2h 3m 4s.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  # Yellow previous command duration.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$yellow

  # Grey Git prompt. This makes stale prompts indistinguishable from up-to-date ones.
  typeset -g POWERLEVEL9K_VCS_FOREGROUND=$grey

  # Disable async loading indicator to make directories that aren't Git repositories
  # indistinguishable from large Git repositories without known state.
  typeset -g POWERLEVEL9K_VCS_LOADING_TEXT=

  # Don't wait for Git status even for a millisecond, so that prompt always updates
  # asynchronously when Git state changes.
  typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0

  # Cyan ahead/behind arrows.
  typeset -g POWERLEVEL9K_VCS_{INCOMING,OUTGOING}_CHANGESFORMAT_FOREGROUND=$cyan
  # Don't show remote branch, current tag or stashes.
  typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind)
  # Don't show the branch icon.
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
  # When in detached HEAD state, show @commit where branch normally goes.
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
  # Don't show staged, unstaged, untracked indicators.
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED}_ICON=
  # Show '*' when there are staged, unstaged or untracked files.
  typeset -g POWERLEVEL9K_VCS_DIRTY_ICON='*'
  # Show '⇣' if local branch is behind remote.
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=':⇣'
  # Show '⇡' if local branch is ahead of remote.
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=':⇡'
  # Don't show the number of commits next to the ahead/behind arrows.
  typeset -g POWERLEVEL9K_VCS_{COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=1

  # Custom git formatter that disables git status in jj repos
  # This prevents showing both git and jj status in colocated repos
  function my_git_formatter() {
    emulate -L zsh -o extended_glob

    # Skip git status in jj repositories - let jj segment handle it
    if [[ -n ./(../)#(.jj)(#qN/) ]]; then
      typeset -g my_git_format=""
      return
    fi

    if [[ -n $P9K_CONTENT ]]; then
      typeset -g my_git_format=$P9K_CONTENT
      return
    fi

    if (( $1 )); then
      local       meta='%244F'
      local      clean='%2F'
      local   modified='%178F'
      local  untracked='%39F'
      local conflicted='%196F'
    else
      local       meta='%244F'
      local      clean='%244F'
      local   modified='%244F'
      local  untracked='%244F'
      local conflicted='%244F'
    fi

    local status_color
    if (( VCS_STATUS_NUM_UNTRACKED )); then
      status_color='%3F'
    elif (( VCS_STATUS_COMMITS_AHEAD && VCS_STATUS_COMMITS_BEHIND )); then
      status_color='%1F'
    elif (( VCS_STATUS_COMMITS_AHEAD )); then
      status_color='%6F'
    elif (( VCS_STATUS_COMMITS_BEHIND )); then
      status_color='%5F'
    else
      status_color='%2F'
    fi

    local res
    local where
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      res+="${status_color}"
      where=${(V)VCS_STATUS_LOCAL_BRANCH}
    elif [[ -n $VCS_STATUS_TAG ]]; then
      res+="${meta}#"
      where=${(V)VCS_STATUS_TAG}
    fi

    (( $#where > 32 )) && where[13,-13]="…"
    res+="${where//\%/%%}"

    if [[ -z $where ]]; then
      local name
      # Suppress stderr as defensive fix - this function shouldn't be called
      # outside a git repo, but prevent error output if it somehow is
      name=$(command git name-rev --name-only --no-undefined --always HEAD 2>/dev/null)
      name="${name#tags/}"
      name="${name#remotes/}"
      res+="${status_color}${(V)name}"
    fi

    if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
      res+="${meta}:${clean}${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}"
    fi

    (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}⇣${VCS_STATUS_COMMITS_BEHIND}"
    (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
    (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}"
    (( VCS_STATUS_STASHES        )) && res+=" ${clean}*${VCS_STATUS_STASHES}"
    [[ -n $VCS_STATUS_ACTION     ]] && res+=" ${conflicted}${VCS_STATUS_ACTION}"
    (( VCS_STATUS_NUM_CONFLICTED )) && res+=" ${conflicted}~${VCS_STATUS_NUM_CONFLICTED}"
    (( VCS_STATUS_NUM_STAGED     )) && res+=" ${modified}+${VCS_STATUS_NUM_STAGED}"
    (( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
    (( VCS_STATUS_NUM_UNTRACKED  )) && res+=" ${untracked}?${VCS_STATUS_NUM_UNTRACKED}"

    typeset -g my_git_format=$res
  }
  functions -M my_git_formatter 2>/dev/null

  # Use custom git formatter
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter(1)))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION='${$((my_git_formatter(0)))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1

  # Grey current time.
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$grey
  # Format for the current time: 09:51:02. See `man 3 strftime`.
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M:%S %p}'
  # If set to true, time will update when you hit enter. This way prompts for the past
  # commands will contain the start times of their commands rather than the end times of
  # their preceding commands.
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # Transient prompt works similarly to the builtin transient_rprompt option. It trims down prompt
  # when accepting a command line. Supported values:
  #
  #   - off:      Don't change prompt when accepting a command line.
  #   - always:   Trim down prompt when accepting a command line.
  #   - same-dir: Trim down prompt when accepting a command line unless this is the first command
  #               typed after changing current working directory.
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt mode.
  #
  #   - off:     Disable instant prompt. Choose this if you've tried instant prompt and found
  #              it incompatible with your zsh configuration files.
  #   - quiet:   Enable instant prompt and don't print warnings when detecting console output
  #              during zsh initialization. Choose this if you've read and understood
  #              https://github.com/romkatv/powerlevel10k#instant-prompt.
  #   - verbose: Enable instant prompt and print a warning when detecting console output during
  #              zsh initialization. Choose this if you've never tried instant prompt, haven't
  #              seen the warning, or if you are unsure what this all means.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
  # For example, you can type POWERLEVEL9K_BACKGROUND=red and see your prompt turn red. Hot reload
  # can slow down prompt by 1-2 milliseconds, so it's better to keep it turned off unless you
  # really need it.
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # ============================================================================
  # JJ (Jujutsu) Async Prompt - based on André Arko's implementation
  # https://andre.arko.net/2025/06/20/a-jj-prompt-for-powerlevel10k/
  # ============================================================================
  #
  # Prompt sections (comment out sections you don't want):
  # - jj_add:    snapshot changes to jj (no output)
  # - jj_at:     bookmark name and distance from @  | main›1
  # - jj_remote: count changes ahead/behind remote  | ⇣2⇡1
  # - jj_change: the current jj change ID           | kkor
  # - jj_desc:   current change description         | first line (or pencil icon)
  # - jj_status: counts of added/removed/modified   | +1 -4 ^2
  # - jj_op:     the current jj operation ID        | b44825e56a5a (disabled by default)

  function jj_status() {
    emulate -L zsh
    cd "$1"

    local grey='%244F'
    local green='%2F'
    local blue='%39F'
    local red='%196F'
    local yellow='%3F'
    local cyan='%6F'
    local magenta='%5F'

    ## jj_add
    jj --at-operation=@ debug snapshot


    ## jj_at
    local branch=$(jj --ignore-working-copy --at-op=@ --no-pager log --no-graph --limit 1 -r "
      coalesce(
        heads(::@ & (bookmarks() | remote_bookmarks() | tags())),
        heads(@:: & (bookmarks() | remote_bookmarks() | tags())),
        trunk()
      )" -T "separate(' ', bookmarks, tags)" 2> /dev/null | cut -d ' ' -f 1)

    if [[ -n $branch ]]; then
      [[ $branch =~ "\*$" ]] && branch=${branch::-1}

      local VCS_STATUS_COMMITS_AFTER=$(jj --ignore-working-copy --at-op=@ --no-pager log --no-graph -r "$branch..@ & (~empty() | merges())" -T '"n"' 2> /dev/null | wc -c | tr -d ' ')
      local VCS_STATUS_COMMITS_BEFORE=$(jj --ignore-working-copy --at-op=@ --no-pager log --no-graph -r "@..$branch & (~empty() | merges())" -T '"n"' 2> /dev/null | wc -c | tr -d ' ')

      # Get remote tracking info
      local counts=($(jj --ignore-working-copy --at-op=@ --no-pager bookmark list -r $branch -T '
        if(remote,
          separate(" ",
            name ++ "@" ++ remote,
            coalesce(tracking_ahead_count.exact(), tracking_ahead_count.lower()),
            coalesce(tracking_behind_count.exact(), tracking_behind_count.lower()),
            if(tracking_ahead_count.exact(), "0", "+"),
            if(tracking_behind_count.exact(), "0", "+"),
          ) ++ "\n"
        )
      '))

      local VCS_STATUS_LOCAL_BRANCH=$branch
      local VCS_STATUS_COMMITS_AHEAD=$counts[2]
      local VCS_STATUS_COMMITS_BEHIND=$counts[3]
      local VCS_STATUS_COMMITS_AHEAD_PLUS=$counts[4]
      local VCS_STATUS_COMMITS_BEHIND_PLUS=$counts[5]
    fi

    # Color bookmark based on sync status with remote
    local status_color=${green}
    (( VCS_STATUS_COMMITS_AHEAD )) && status_color=${cyan}
    (( VCS_STATUS_COMMITS_BEHIND )) && status_color=${magenta}
    (( VCS_STATUS_COMMITS_AHEAD && VCS_STATUS_COMMITS_BEHIND )) && status_color=${red}

    local res
    local where=${(V)VCS_STATUS_LOCAL_BRANCH}
    # Truncate long branch names: first 12 … last 12
    (( $#where > 32 )) && where[13,-13]="…"
    res+="${status_color}${where//\%/%%}"

    # ‹42 if before the local bookmark
    (( VCS_STATUS_COMMITS_BEFORE )) && res+="‹${VCS_STATUS_COMMITS_BEFORE}"
    # ›42 if beyond the local bookmark
    (( VCS_STATUS_COMMITS_AFTER )) && res+="›${VCS_STATUS_COMMITS_AFTER}"


    ## jj_remote - ahead/behind remote (uncomment to enable)
    # # ⇣42 if behind the remote
    # (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${green}⇣${VCS_STATUS_COMMITS_BEHIND}"
    # (( VCS_STATUS_COMMITS_BEHIND_PLUS )) && res+="${VCS_STATUS_COMMITS_BEHIND_PLUS}"
    # # ⇡42 if ahead of the remote
    # (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
    # (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${green}⇡${VCS_STATUS_COMMITS_AHEAD}"
    # (( VCS_STATUS_COMMITS_AHEAD_PLUS )) && res+="${VCS_STATUS_COMMITS_AHEAD_PLUS}"


    ## jj_change - change ID with color coding
    IFS="#" local change=($(jj --ignore-working-copy --at-op=@ --no-pager log --no-graph --limit 1 -r "@" -T '
      separate("#",
        change_id.shortest(4).prefix(),
        coalesce(change_id.shortest(4).rest(), "\0"),
        commit_id.shortest(4).prefix(),
        coalesce(commit_id.shortest(4).rest(), "\0"),
        concat(
          if(conflict, "💥"),
          if(divergent, "🚧"),
          if(hidden, "👻"),
          if(immutable, "🔒"),
        ),
      )'))
    local VCS_STATUS_CHANGE=($change[1] $change[2])
    local VCS_STATUS_COMMIT=($change[3] $change[4])
    local VCS_STATUS_ACTION=$change[5]

    # Change ID: magenta bold prefix + grey rest
    res+=" ${magenta}${VCS_STATUS_CHANGE[1]}${grey}${VCS_STATUS_CHANGE[2]}"
    # Status icons: 💥🚧👻🔒
    [[ -n $VCS_STATUS_ACTION ]] && res+=" ${red}${VCS_STATUS_ACTION}"
    # Commit ID (uncomment to show): blue bold prefix + grey rest
    # res+=" ${blue}${VCS_STATUS_COMMIT[1]}${grey}${VCS_STATUS_COMMIT[2]}"


    ## jj_desc - description or pencil icon if empty but has changes (truncated to 30 chars)
    local VCS_STATUS_MESSAGE=$(jj --ignore-working-copy --at-op=@ --no-pager log --no-graph --limit 1 -r "@" -T "coalesce(description.first_line(), if(!empty, '\Uf040 '))")
    (( $#VCS_STATUS_MESSAGE > 30 )) && VCS_STATUS_MESSAGE="${VCS_STATUS_MESSAGE:0:30}…"
    [[ -n $VCS_STATUS_MESSAGE ]] && res+=" ${green}${VCS_STATUS_MESSAGE}"


    ## jj_status - file change counts
    local VCS_STATUS_CHANGES=($(jj log --ignore-working-copy --at-op=@ --no-graph --no-pager -r @ -T "diff.summary()" 2> /dev/null | awk 'BEGIN {a=0;d=0;m=0} /^A / {a++} /^D / {d++} /^M / {m++} /^R / {m++} /^C / {a++} END {print(a,d,m)}'))
    (( VCS_STATUS_CHANGES[1] )) && res+=" %F{green}+${VCS_STATUS_CHANGES[1]}"
    (( VCS_STATUS_CHANGES[2] )) && res+=" %F{red}-${VCS_STATUS_CHANGES[2]}"
    (( VCS_STATUS_CHANGES[3] )) && res+=" ${yellow}^${VCS_STATUS_CHANGES[3]}"


    ## jj_op - operation ID (uncomment to enable)
    # local VCS_STATUS_OP=$(jj --ignore-working-copy --at-op=@ --no-pager op log --limit 1 --no-graph -T "id.short()")
    # [[ -n $VCS_STATUS_OP ]] && res+=" ${blue}${VCS_STATUS_OP}"


    echo $res
  }

  function jj_status_callback() {
    emulate -L zsh
    if [[ $2 -ne 0 ]]; then
      typeset -g p10k_jj_status=
    else
      typeset -g p10k_jj_status="$3"
    fi
    typeset -g p10k_jj_status_stale= p10k_jj_status_updated=1 p10k_jj_placeholder=
    p10k display -r
  }

  async_start_worker        jj_status_worker -u
  async_unregister_callback jj_status_worker
  async_register_callback   jj_status_worker jj_status_callback

  function prompt_jj() {
    emulate -L zsh -o extended_glob
    (( $+commands[jj] )) || return
    [[ -n ./(../)#(.jj)(#qN/) ]] || return

    typeset -g p10k_jj_status_stale=1 p10k_jj_status_updated=

    # Set placeholder if no cached status yet
    if [[ -z $p10k_jj_status ]]; then
      typeset -g p10k_jj_placeholder=1
      typeset -g p10k_jj_quick=$(jj --ignore-working-copy --no-pager log --no-graph --limit 1 -r "@" \
        -T 'separate(" ", coalesce(bookmarks, ""), change_id.shortest(4))' 2>/dev/null)
      [[ -z $p10k_jj_quick ]] && typeset -g p10k_jj_quick="jj"
      p10k_jj_quick+=" …"  # Loading indicator
    fi

    # Show placeholder if no cache (cleared by callback)
    p10k segment -f grey -c '$p10k_jj_placeholder' -e -t '$p10k_jj_quick'
    # Show stale cached status while updating
    p10k segment -f grey -c '$p10k_jj_status_stale' -e -t '$p10k_jj_status'
    # Show fresh status when async completes
    p10k segment -c '$p10k_jj_status_updated' -e -t '$p10k_jj_status'

    async_job jj_status_worker jj_status $PWD
  }

  # If p10k is already loaded, reload configuration.
  # This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
