# modules/desktop/term/ghostty.nix
#
# Ghostty terminal emulator configuration
#
# KEY DESIGN DECISION: behavior.conf is read from the static config file and has
# PATH injection appended via nix. This solves the problem where Ghostty's `command`
# directive runs before shell profile loading, so nix paths aren't in PATH and tmux
# isn't found.
#
# The solution: Use Ghostty's `env=PATH=...` directive to explicitly set PATH with
# all nix-managed directories, using ${config.user.name} for multi-host support.
#
# Static config files (macos.conf, ui.conf) remain as symlinked files for easy
# direct editing. behavior.conf and keybindings.conf are generated to allow other
# modules to append configuration.
#
# Pattern (similar to modules/shell/zsh/default.nix):
#   - keybindingsInit: inline keybinding text from other modules
#   - keybindingFiles: list of keybinding files to include
#   - configInit: inline config text from other modules
{
  config,
  inputs,
  lib,
  isDarwin,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.desktop.term.ghostty;
  inherit (config.dotfiles) configDir;

  # Build PATH with all nix-managed directories
  # This ensures commands like `tmux` are found when Ghostty runs its `command` directive,
  # even though shell profile loading is skipped (--noprofile --norc flags)
  nixPath = concatStringsSep ":" [
    "${config.user.home}/.nix-profile/bin"
    "/etc/profiles/per-user/${config.user.name}/bin"
    "/run/current-system/sw/bin"
    "/nix/var/nix/profiles/default/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];
in
{
  options.modules.desktop.term.ghostty = with types; {
    enable = mkBoolOpt false;

    keybindingsInit = mkOpt' lines "" ''
      Ghostty keybinding lines to be appended to keybindings.conf.
      Other modules can add keybindings here.
    '';

    keybindingFiles = mkOpt (listOf (either str path)) [ "${configDir}/ghostty/keybindings.conf" ];

    configInit = mkOpt' lines "" ''
      Ghostty config lines to be appended to the main config.
      Other modules can add configuration here.
    '';
  };

  config = mkIf cfg.enable {
    # On macOS, ghostty is installed via Homebrew cask
    # On Linux, use the Nix package
    user.packages = optionals (!isDarwin) [ inputs.ghostty.packages.x86_64-linux.default ];

    # ghostty terminfo isn't supported over ssh, so revert to a known one
    modules.shell.zsh.rcInit = ''
      [ "$TERM" = ghostty ] && [ -n "$SSH_CONNECTION" ] && export TERM=xterm-256color
    '';

    # Ensure base keybindings file is included first
    modules.desktop.term.ghostty.keybindingFiles = mkBefore [
      "${configDir}/ghostty/keybindings.conf"
    ];

    home-manager.users.${config.user.name} = {
      # Symlink static config files that don't need generation
      home.file = {
        ".config/ghostty/macos.conf".source = "${configDir}/ghostty/macos.conf";
        ".config/ghostty/ui.conf".source = "${configDir}/ghostty/ui.conf";
      };

      xdg.configFile = {
        # Generate main config from base file + any configInit from other modules
        "ghostty/config".text =
          builtins.readFile "${configDir}/ghostty/config"
          + optionalString (cfg.configInit != "") ''

            # Additional config (auto-generated by nix)
            ${cfg.configInit}
          '';

        # Generate keybindings.conf by concatenating all keybinding files + init text
        "ghostty/keybindings.conf".text = ''
          # Ghostty Keybindings (auto-generated by nix)
          # Base config: config/ghostty/keybindings.conf
          # Additional files and init text added by other modules

          ${concatMapStrings (path: ''
            ${builtins.readFile path}
          '') (lib.unique cfg.keybindingFiles)}
          ${optionalString (cfg.keybindingsInit != "") ''
            # Inline keybindings from modules
            ${cfg.keybindingsInit}
          ''}
        '';

        # Generate behavior.conf with PATH injection appended
        # This allows editing config/ghostty/behavior.conf directly while still
        # injecting the nix PATH needed for tmux discovery.
        "ghostty/behavior.conf".text = builtins.readFile "${configDir}/ghostty/behavior.conf" + ''

          # ============================================================================
          # PATH injection for nix-managed packages (auto-generated by nix)
          # Edit modules/desktop/term/ghostty.nix to modify this section
          # ============================================================================
          # Ghostty's command runs before shell profiles load (--noprofile --norc),
          # so we explicitly set PATH to include nix-managed directories.
          # This enables commands like `tmux` to be found.
          env=PATH=${nixPath}
        '';
      };
    };
  };
}
