# modules/desktop/term/ghostty.nix
#
# Ghostty terminal emulator configuration
#
# KEY DESIGN DECISION: behavior.conf is read from the static config file and has
# PATH injection appended via nix. This solves the problem where Ghostty's `command`
# directive runs before shell profile loading, so nix paths aren't in PATH and tmux
# isn't found.
#
# The solution: Use Ghostty's `env=PATH=...` directive to explicitly set PATH with
# all nix-managed directories, using ${config.user.name} for multi-host support.
#
# Static config files (macos.conf, ui.conf) remain as symlinked files for easy
# direct editing. behavior.conf and keybindings.conf are generated to allow other
# modules to append configuration.
#
# Pattern (similar to modules/shell/zsh/default.nix):
#   - keybindingsInit: inline keybinding text from other modules
#   - keybindingFiles: list of keybinding files to include
#   - configInit: inline config text from other modules
{
  config,
  inputs,
  lib,
  pkgs,
  isDarwin,
  ...
}:
with lib;
with lib.my;
let
  cfg = config.modules.desktop.term.ghostty;
  stylixCfg = config.modules.theme.stylix;
  stylixColors = config.lib.stylix.colors;
  inherit (config.dotfiles) configDir;

  appleScriptString = value: replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ] value;

  # Build PATH with user-level bins plus nix-managed directories.
  # Ghostty's `command` runs before shell profile loading, so launchers like
  # bun-installed `jmux` must be discoverable here too.
  nixPath = concatStringsSep ":" [
    "/etc/profiles/per-user/${config.user.name}/bin"
    "/run/current-system/sw/bin"
    "${config.user.home}/.nix-profile/bin"
    config.dotfiles.binDir
    "${config.user.home}/.pi/agent/bin"
    "${config.user.home}/.bun/bin"
    "${config.user.home}/.local/bin"
    "${config.user.home}/.pixi/bin"
    "${config.user.home}/.cargo/bin"
    "/nix/var/nix/profiles/default/bin"
    "/usr/local/bin"
    "/usr/bin"
    "/bin"
    "/usr/sbin"
    "/sbin"
  ];

  # Keep Ghostty/Herdr child processes from inheriting stale terminfo paths.
  # Codex doctor currently fails if any TERMINFO_DIRS entry is missing.
  terminfoPath = concatStringsSep ":" [
    "${config.user.home}/.terminfo"
    "/etc/profiles/per-user/${config.user.name}/share/terminfo"
    "/run/current-system/sw/share/terminfo"
    "/usr/share/terminfo"
  ];

  useHerdr = config.modules.shell.herdr.enable;
  useJmux = config.modules.shell.tmux.enable && config.modules.shell.tmux.jmux.enable;
  ghosttyStartupCommand =
    if useHerdr then
      "${config.user.home}/.config/tmux/open-herdr.sh"
    else if useJmux then
      "${config.user.home}/.config/tmux/open-jmux.sh"
    else
      "tmux new-session -A -s home";

  ghosttyConfigText =
    builtins.readFile "${configDir}/ghostty/config"
    + optionalString (cfg.configInit != "") ''

      # Additional config (auto-generated by nix)
      ${cfg.configInit}
    '';
in
{
  options.modules.desktop.term.ghostty = with types; {
    enable = mkBoolOpt false;

    keybindingsInit = mkOpt' lines "" ''
      Ghostty keybinding lines to be appended to keybindings.conf.
      Other modules can add keybindings here.
    '';

    keybindingFiles = mkOpt (listOf (either str path)) [ "${configDir}/ghostty/keybindings.conf" ];

    configInit = mkOpt' lines "" ''
      Ghostty config lines to be appended to the main config.
      Other modules can add configuration here.
    '';

    macosTerminalProfileName = mkOpt str "Ghostty Match";
  };

  config = mkIf cfg.enable {
    # Install Ghostty via Nix on all platforms.
    # macOS uses ghostty-bin (official DMG repackaged in nixpkgs).
    # Linux uses the upstream Ghostty flake package.
    # Install Ghostty from Nix.
    # - macOS: system package (exposes app bundle in /Applications/Nix Apps)
    # - Linux: user package from upstream Ghostty flake
    environment.systemPackages = optionals isDarwin [ pkgs.ghostty-bin ];
    user.packages = optionals (!isDarwin) [ inputs.ghostty.packages.x86_64-linux.default ];

    # ghostty terminfo isn't available everywhere (ssh, hermes, subprocesses)
    # fall back to xterm-256color when the terminfo entry is missing
    modules.shell.zsh.rcInit = ''
      [ "$TERM" = ghostty ] && ! infocmp ghostty >/dev/null 2>&1 && export TERM=xterm-256color
    '';

    # Ensure base keybindings file is included first
    modules.desktop.term.ghostty.keybindingFiles = mkBefore [
      "${configDir}/ghostty/keybindings.conf"
    ];

    home-manager.users.${config.user.name} =
      { lib, ... }:
      {
        # Symlink static config files that don't need generation
        home.file = {
          ".config/ghostty/macos.conf".source = "${configDir}/ghostty/macos.conf";
          ".config/ghostty/ui.conf".source = "${configDir}/ghostty/ui.conf";
        };

        home.activation.ghostty-remove-legacy-macos-config = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          # Ghostty may have created this old macOS-native config before the XDG
          # config existed. If present, it shadows ~/.config/ghostty/config for
          # GUI launches, so keep it absent and let XDG be the only config source.
          legacy_config="$HOME/Library/Application Support/com.mitchellh.ghostty/config"
          if [ -e "$legacy_config" ] || [ -L "$legacy_config" ]; then
            rm -f "$legacy_config"
          fi
        '';

        home.activation.ghostty-set-terminal-profile = mkIf (isDarwin && stylixCfg.enable) (
          lib.hm.dag.entryAfter [ "writeBoundary" ] ''
            # Keep Terminal.app visually aligned with the Ghostty/Stylix font and palette.
            if [ -x /usr/bin/osascript ]; then
              to_rgb16() {
                hex=$1
                hex=''${hex#\#}
                r=''${hex:0:2}
                g=''${hex:2:2}
                b=''${hex:4:2}
                printf '{%d, %d, %d}' "$((16#$r * 257))" "$((16#$g * 257))" "$((16#$b * 257))"
              }

              background=$(to_rgb16 '${stylixColors.base00}')
              foreground=$(to_rgb16 '${stylixColors.base05}')
              bold=$(to_rgb16 '${stylixColors.base07}')
              cursor=$(to_rgb16 '${stylixColors.base0D}')
              /usr/bin/osascript \
                -e 'tell application "Terminal"' \
                -e 'try' \
                -e 'make new settings set with properties {name:"${appleScriptString cfg.macosTerminalProfileName}"}' \
                -e 'end try' \
                -e 'set font name of settings set "${appleScriptString cfg.macosTerminalProfileName}" to "${appleScriptString stylixCfg.fonts.monospace.name}"' \
                -e 'set font size of settings set "${appleScriptString cfg.macosTerminalProfileName}" to ${toString stylixCfg.fonts.sizes.terminal}' \
                -e "set background color of settings set \"${appleScriptString cfg.macosTerminalProfileName}\" to $background" \
                -e "set normal text color of settings set \"${appleScriptString cfg.macosTerminalProfileName}\" to $foreground" \
                -e "set bold text color of settings set \"${appleScriptString cfg.macosTerminalProfileName}\" to $bold" \
                -e "set cursor color of settings set \"${appleScriptString cfg.macosTerminalProfileName}\" to $cursor" \
                -e 'set default settings to settings set "${appleScriptString cfg.macosTerminalProfileName}"' \
                -e 'set startup settings to settings set "${appleScriptString cfg.macosTerminalProfileName}"' \
                -e 'if (count of windows) > 0 then' \
                -e 'repeat with w in windows' \
                -e 'repeat with t in tabs of w' \
                -e 'set current settings of t to settings set "${appleScriptString cfg.macosTerminalProfileName}"' \
                -e 'end repeat' \
                -e 'end repeat' \
                -e 'end if' \
                -e 'end tell' >/dev/null 2>&1 || true
            fi
          ''
        );

        xdg.configFile = {
          # Generate main config from base file + any configInit from other modules
          "ghostty/config".text = ghosttyConfigText;

          # Generate keybindings.conf by concatenating all keybinding files + init text
          "ghostty/keybindings.conf".text = ''
            # Ghostty Keybindings (auto-generated by nix)
            # Base config: config/ghostty/keybindings.conf
            # Additional files and init text added by other modules

            ${concatMapStrings (path: ''
              ${builtins.readFile path}
            '') (lib.unique cfg.keybindingFiles)}
            ${optionalString (cfg.keybindingsInit != "") ''
              # Inline keybindings from modules
              ${cfg.keybindingsInit}
            ''}
          '';

          # Generate behavior.conf with PATH injection appended.
          # This allows editing config/ghostty/behavior.conf directly while still
          # injecting the nix PATH needed for tmux/jmux discovery.
          "ghostty/behavior.conf".text = builtins.readFile "${configDir}/ghostty/behavior.conf" + ''

            # ============================================================================
            # PATH injection for Ghostty startup commands (auto-generated by nix)
            # Edit modules/desktop/term/ghostty.nix to modify this section
            # ============================================================================
            # Ghostty's command runs before shell profiles load (--noprofile --norc),
            # so we explicitly set PATH to include user and nix-managed directories.
            env=PATH=${nixPath}
            env=TERMINFO_DIRS=${terminfoPath}

            # Keep Ghostty running if its Herdr-owned surface exits.
            quit-after-last-window-closed = ${if useHerdr then "false" else "true"}

            # Startup command override (auto-generated by nix)
            # Startup owner: Herdr when enabled; otherwise the next enabled owner directly.
            command = ${ghosttyStartupCommand}
          '';
        };
      };
  };
}
