invert = true
# use systemd timer instead
auto_sync = false
# nixpkgs
update_check = false

style = "auto"

keymap_mode = "auto"

common_subcommands = [
  "cargo",
  "go",
  "git",
  "npm",
  "yarn",
  "pnpm",
  "kubectl",
  "nextflow",
  "nf-test",
]
