.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-SYNC" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-sync\fR \- Fetch git objects from upstream and update branches\.
.
.SH "SYNOPSIS"
\fBhub sync\fR
.
.IP "\(bu" 4
If the local branch is outdated, fast\-forward it;
.
.IP "\(bu" 4
If the local branch contains unpushed work, warn about it;
.
.IP "\(bu" 4
If the branch seems merged and its upstream branch was deleted, delete it\.
.
.IP "" 0
.
.P
If a local branch doesn`t have any upstream configuration, but has a same\-named branch on the remote, treat that as its upstream branch\.
.
.SH "SEE ALSO"
hub(1), git\-fetch(1)
