.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-CHECKOUT" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-checkout\fR \- Check out the head of a pull request as a local branch\.
.
.SH "SYNOPSIS"
\fBhub checkout\fR \fIPULLREQ\-URL\fR [\fIBRANCH\fR]
.
.SH "EXAMPLES"
.
.nf

$ hub checkout https://github\.com/jingweno/gh/pull/73
> git fetch origin pull/73/head:jingweno\-feature
> git checkout jingweno\-feature
.
.fi
.
.SH "SEE ALSO"
hub\-merge(1), hub\-am(1), hub(1), git\-checkout(1)
