.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-SUBMODULE" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-submodule\fR \- Add a git submodule for a GitHub repository\.
.
.SH "SYNOPSIS"
\fBhub submodule\fR add [\-p] [\fIOPTIONS\fR] [\fIUSER\fR/]\fIREPOSITORY\fR \fIDESTINATION\fR
.
.SH "EXAMPLES"
.
.nf

$ hub submodule add jingweno/gh vendor/gh
> git submodule add git://github\.com/jingweno/gh\.git vendor/gh
.
.fi
.
.SH "SEE ALSO"
hub\-remote(1), hub(1), git\-submodule(1)
