.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-ALIAS" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-alias\fR \- Show shell instructions for wrapping git\.
.
.SH "SYNOPSIS"
\fBhub alias\fR [\-s] [\fISHELL\fR]
.
.SH "OPTIONS"
.
.TP
\-s
Output shell script suitable for \fBeval\fR\.
.
.TP
\fISHELL\fR
Specify the type of shell (default: "$SHELL" environment variable)\.
.
.SH "SEE ALSO"
hub(1)
