.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-COMPARE" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-compare\fR \- Open a GitHub compare page in a web browser\.
.
.SH "SYNOPSIS"
\fBhub compare\fR [\-u] [\-b \fIBASE\fR] [\fIUSER\fR] [[\fISTART\fR\.\.\.]\fIEND\fR]
.
.SH "OPTIONS"
.
.TP
\-u
Print the URL instead of opening it\.
.
.TP
\-b \fIBASE\fR
Base branch to compare\.
.
.TP
[\fISTART\fR\.\.\.]\fIEND\fR
Branch names, tag names, or commit SHAs specifying the range to compare\. \fIEND\fR defaults to the current branch name\.
.
.IP
If a range with two dots (\fBA\.\.B\fR) is given, it will be transformed into a range with three dots\.
.
.SH "EXAMPLES"
.
.nf

$ hub compare refactor
> open https://github\.com/USER/REPO/compare/refactor

$ hub compare v1\.0\.\.v1\.1
> open https://github\.com/USER/REPO/compare/v1\.0\.\.\.v1\.1

$ hub compare \-u jingweno feature
> echo https://github\.com/jingweno/REPO/compare/feature
.
.fi
.
.SH "SEE ALSO"
hub\-browse(1), hub(1)
