.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-PR" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-pr\fR \- Manage GitHub pull requests for the current project\.
.
.SH "SYNOPSIS"
\fBhub pr\fR list [\-s \fISTATE\fR] [\-h \fIHEAD\fR] [\-b \fIBASE\fR] [\-o \fISORT_KEY\fR [\- [\-L \fILIMIT\fR]
.
.br
\fBhub pr\fR checkout \fIPR\-NUMBER\fR [\fIBRANCH\fR]
.
.SH "COMMANDS"
.
.TP
\fIlist\fR
List pull requests in the current project\.
.
.TP
\fIcheckout\fR
Check out the head of a pull request in a new branch\.
.
.SH "OPTIONS"
.
.TP
\-s, \-\-state \fISTATE\fR
Display pull requests with state \fISTATE\fR (default: "open")\.
.
.TP
\-f, \-\-format \fIFORMAT\fR
Pretty print the list of pull requests using format \fIFORMAT\fR (default: "%sC%>(8)%i%Creset %t% l%n")\. See the "PRETTY FORMATS" section of the git\-log manual for some additional details on how placeholders are used in format\. The available placeholders are:
.
.IP
%I: pull request number
.
.IP
%i: pull request number prefixed with "#"
.
.IP
%U: the URL of this pull request
.
.IP
%S: state (i\.e\. "open", "closed")
.
.IP
%sC: set color to red or green, depending on pull request state\.
.
.IP
%t: title
.
.IP
%l: colored labels
.
.IP
%L: raw, comma\-separated labels
.
.IP
%b: body
.
.IP
%B: base branch
.
.IP
%H: head branch
.
.IP
%au: login name of author
.
.IP
%as: comma\-separated list of assignees
.
.IP
%Mn: milestone number
.
.IP
%Mt: milestone title
.
.IP
%NC: number of comments
.
.IP
%Nc: number of comments wrapped in parentheses, or blank string if zero\.
.
.IP
%cD: created date\-only (no time of day)
.
.IP
%cr: created date, relative
.
.IP
%ct: created date, UNIX timestamp
.
.IP
%cI: created date, ISO 8601 format
.
.IP
%uD: updated date\-only (no time of day)
.
.IP
%ur: updated date, relative
.
.IP
%ut: updated date, UNIX timestamp
.
.IP
%uI: updated date, ISO 8601 format
.
.TP
\-o, \-\-sort \fISORT_KEY\fR
Sort displayed issues by "created" (default), "updated", "popularity", or "long\-running"\.
.
.TP
\-^ \-\-sort\-ascending
Sort by ascending dates instead of descending\.
.
.TP
\-L, \-\-limit \fILIMIT\fR
Display only the first \fILIMIT\fR issues\.
.
.SH "SEE ALSO"
hub\-issue(1), hub\-pull\-request(1), hub(1)
