.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-REMOTE" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-remote\fR \- Add a git remote for a GitHub repository\.
.
.SH "SYNOPSIS"
\fBhub remote\fR add [\-p] [\fIOPTIONS\fR] \fIUSER\fR[/\fIREPOSITORY\fR]
.
.br
\fBhub remote\fR set\-url [\-p] [\fIOPTIONS\fR] \fINAME\fR \fIUSER\fR[/\fIREPOSITORY\fR]
.
.SH "OPTIONS"
.
.TP
\-p
(Deprecated) Use the \fBssh:\fR protocol for the remote URL\.
.
.TP
\fIUSER\fR[/\fIREPOSITORY\fR]
If \fIUSER\fR is "origin", that value will be substituted for your GitHub username\. \fIREPOSITORY\fR defaults to the name of the current working directory\.
.
.SH "EXAMPLES"
.
.nf

$ hub remote add jingweno
> git remote add jingweno git://github\.com/jingweno/REPO\.git

$ hub remote add origin
> git remote add origin git://github\.com/USER/REPO\.git
.
.fi
.
.SH "SEE ALSO"
hub\-fork(1), hub(1), git\-remote(1)
