.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-MERGE" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-merge\fR \- Merge a pull request with a message like the GitHub Merge Button\.
.
.SH "SYNOPSIS"
\fBhub merge\fR \fIPULLREQ\-URL\fR
.
.SH "EXAMPLES"
.
.nf

$ hub merge https://github\.com/jingweno/gh/pull/73
> git fetch origin refs/pull/73/head
> git merge FETCH_HEAD \-\-no\-ff \-m "Merge pull request #73 from jingweno/feature\.\.\."
.
.fi
.
.SH "SEE ALSO"
hub\-checkout(1), hub(1), git\-merge(1)
