.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-RELEASE" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-release\fR \- Manage GitHub releases\.
.
.SH "SYNOPSIS"
\fBhub release\fR [\-\-include\-drafts] [\-\-exclude\-prereleases] [\-L \fILIMIT\fR]
.
.br
\fBhub release\fR show \fITAG\fR
.
.br
\fBhub release\fR create [\-dpoc] [\-a \fIFILE\fR] [\-m \fIMESSAGE\fR|\-F \fIFILE\fR] [\-t \fITARGET\fR] \fITAG\fR
.
.br
\fBhub release\fR edit [\fIoptions\fR] \fITAG\fR
.
.br
\fBhub release\fR delete \fITAG\fR
.
.SH "COMMANDS"
With no arguments, shows a list of existing releases\.
.
.P
With \fB\-\-include\-drafts\fR, include draft releases in the listing\. With \fB\-\-exclude\-prereleases\fR, exclude non\-stable releases from the listing\.
.
.TP
\fIshow\fR
Show GitHub release notes for \fITAG\fR\.
.
.IP
With \fB\-\-show\-downloads\fR, include the "Downloads" section\.
.
.TP
\fIcreate\fR
Create a GitHub release for the specified \fITAG\fR name\. If git tag \fITAG\fR doesn`t exist, it will be created at \fITARGET\fR (default: current branch)\.
.
.TP
\fIedit\fR
Edit the GitHub release for the specified \fITAG\fR name\. Accepts the same options as \fIcreate\fR command\. Publish a draft with \fB\-\-draft=false\fR\.
.
.IP
When \fIMESSAGE\fR or \fIFILE\fR are not specified, a text editor will open pre\-populated with current release title and body\. To re\-use existing title and body unchanged, pass \fB\-m ""\fR\.
.
.TP
\fIdownload\fR
Download the assets attached to release for the specified \fITAG\fR\.
.
.TP
\fIdelete\fR
Delete the release and associated assets for the specified \fITAG\fR\.
.
.SH "OPTIONS"
.
.TP
\-L, \-\-limit
Display only the first \fILIMIT\fR releases\.
.
.TP
\-d, \-\-draft
Create a draft release\.
.
.TP
\-p, \-\-prerelease
Create a pre\-release\.
.
.TP
\-a, \-\-asset \fIFILE\fR
Attach a file as an asset for this release\.
.
.IP
If \fIFILE\fR is in the "\fIfilename\fR#\fItext\fR" format, the text after the \fB#\fR character is taken as asset label\.
.
.TP
\-m, \-\-message \fIMESSAGE\fR
Use the first line of \fIMESSAGE\fR as release title, and the rest as release description\.
.
.TP
\-F, \-\-file \fIFILE\fR
Read the release title and description from \fIFILE\fR\.
.
.TP
\-e, \-\-edit
Further edit the contents of \fIFILE\fR in a text editor before submitting\.
.
.TP
\-o, \-\-browse
Open the new release in a web browser\.
.
.TP
\-c, \-\-copy
Put the URL of the new release to clipboard instead of printing it\.
.
.TP
\-t, \-\-commitish \fITARGET\fR
A commit SHA or branch name to attach the release to, only used if \fITAG\fR doesn`t already exist (default: main branch)\.
.
.TP
\fITAG\fR
The git tag name for this release\.
.
.SH "SEE ALSO"
hub(1), git\-tag(1)
