.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-CI\-STATUS" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-ci\-status\fR \- Display GitHub Status information for a commit\.
.
.SH "SYNOPSIS"
\fBhub ci\-status\fR [\-v] [\fICOMMIT\fR]
.
.SH "OPTIONS"
.
.TP
\-v
Print detailed report of all status checks and their URLs\.
.
.TP
\fICOMMIT\fR
A commit SHA or branch name (default: "HEAD")\.
.
.P
Exits with one of: success (0), error (1), failure (1), pending (2), no status (3)\.
.
.SH "SEE ALSO"
hub\-pull\-request(1), hub(1)
