.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-AM" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-am\fR \- Replicate commits from a GitHub pull request locally\.
.
.SH "SYNOPSIS"
\fBhub am\fR [\-3] \fIGITHUB\-URL\fR
.
.SH "OPTIONS"
.
.TP
\-3
(Recommended) See git\-am(1)\.
.
.TP
\fIGITHUB\-URL\fR
A URL to a pull request or commit on GitHub\.
.
.SH "EXAMPLES"
.
.nf

$ hub am \-3 https://github\.com/jingweno/gh/pull/55
> curl https://github\.com/jingweno/gh/pull/55\.patch \-o /tmp/55\.patch
> git am \-3 /tmp/55\.patch
.
.fi
.
.SH "SEE ALSO"
hub\-apply(1), hub\-cherry\-pick(1), hub(1), git\-am(1)
