.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HUB\-CHERRY\-PICK" "1" "May 2018" "GITHUB" "Hub Manual"
.
.SH "NAME"
\fBhub\-cherry\-pick\fR \- Cherry\-pick a commit from a fork on GitHub\.
.
.SH "SYNOPSIS"
\fBhub cherry\-pick\fR \fICOMMIT\-URL\fR
.
.br
\fBhub cherry\-pick\fR \fIUSER\fR@\fISHA\fR
.
.SH "SEE ALSO"
hub\-am(1), hub(1), git\-cherry\-pick(1)
