#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  sudo nixos-rebuild switch
  home-manager switch
}

update() {
  sudo nixos-rebuild switch
  nix-env -u
}

link() {
  mklink configuration.nix /etc/nixos/configuration.nix
  mklink modules/* /etc/nixos/modules/*
  mklink services/* /etc/nixos/services/*
  mklink machines/* /etc/nixos/machines/*
  mklink home/* $XDG_CONFIG_HOME/nixpkgs/*
}

# clean() {}

init "$@"
