# Turn off a media player after it's been idle for a configurable duration.
# Optionally restrict to nighttime (goodnight=on).
blueprint:
  name: Media Player Idle Auto-Off
  description: >
    Turn off a media player after it has been idle (or paused) for a
    configurable amount of time.  Optionally only fire during nighttime.
  domain: automation
  input:
    media_player:
      name: Media Player
      description: The media player to monitor.
      selector:
        entity:
          filter:
            - domain: media_player
    idle_minutes:
      name: Idle Duration (minutes)
      description: How long the player must be idle before turning off.
      default: 120
      selector:
        number:
          min: 5
          max: 480
          unit_of_measurement: min
    require_night:
      name: Require Nighttime (optional)
      description: >
        Only turn off when goodnight is on. Set to false to always apply.
      default: false
      selector:
        boolean:

triggers:
  - trigger: state
    entity_id: !input media_player
    to: "idle"
    for:
      minutes: !input idle_minutes
  - trigger: state
    entity_id: !input media_player
    to: "paused"
    for:
      minutes: !input idle_minutes

conditions:
  - condition: template
    value_template: >
      {% set night_only = "require_night" %}
      {{ not night_only or is_state("input_boolean.goodnight", "on") }}

actions:
  - action: media_player.turn_off
    target:
      entity_id: !input media_player
