[theme]
name = "catppuccin"

[ui.toast]
delivery = "herdr"

[keys]
prefix = "ctrl+c"
new_workspace = "w"
previous_tab = "p"
next_tab = "n"

[[keys.command]]
key = "]"
type = "shell"
command = "/Users/emiller/.config/dotfiles/bin/herdr-hunk"

[[keys.command]]
key = "}"
type = "shell"
command = "/Users/emiller/.config/dotfiles/bin/herdr-hunk --tab"
