#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
#source env.zsh

install() {
  if command -v 'npm' >/dev/null; then
    npm install -g solc solium truffle embark
  fi

   case $(_os) in
    # macos) brew install ;;
    # arch) ;;
    # debian) npm install -g solc solium truffle embark ;;
  esac
}

update() {
  npm update solc solium truffle embark
}

# link() {}

# clean() {}

init "$@"
