#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
    # macos) brew install ;;
    # arch) ;;
    debian) npm install -g solc solium truffle
            ;;
  esac
}

update() {
  npm update solc solium truffle
}

# link() {}

# clean() {}

init "$@"
