on: [push]

name: Dead code analysis

jobs:
  deadnix:
    name: Deadnix
      runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: cachix/install-nix-action@v22
          - uses: cachix/cachix-action@v12
            with:
              name: deadnix
          - uses: astro/deadnix-action@main